gip-inclusion/carnet-de-bord

.github/workflows/deactivate.yml
.github/workflows/production.yml
.github/workflows/review.yml
.k8s/components/app.ts
.k8s/components/hasura.ts
CHANGELOG.md
package.json

This reverts commit d0bc565042c3f61d6bb5bce5f2489ee0eee229e2.
Since we found the reason why the `Github registry` was rejecting our packages updates (aka: The 403 problem), we could leave `Harbor` and move back to `ghcr.io`.

fix: Revert registry changes

---

.k8s/__tests__/__snapshots__/kosko generate --env prod.ts.snap
.k8s/environments/prod/app.configmap.yaml
src/global.d.ts
src/lib/config/variables/public.ts
src/lib/tracking/matomo.ts
src/routes/__layout.svelte
src/routes/index.svelte
src/routes/pro/index.svelte

- Ajout du tracker matomo
- modification des redirects pour qu'ils soient fait coté serveur (pour éviter d'avoir la page avant redirection qui remonte dans matomo)
il va falloir tracker a la main les ouvertures de panneaux et les différent formulaire aussi
il faudrait aussi renseigner le la balise title dans nos page
```svelte
<svelte:head>
<title>titre de la page - carnet de bord</title>
</svelte:head>
```
closes  #306

feat: add client tracking

---

src/hooks.ts
src/lib/config/variables/private.ts
src/lib/ui/utils/LoaderIndicator.svelte
src/lib/ui/views/Disconnect.svelte
src/lib/utils/security.ts
src/routes/auth/jwt/[uuid].svelte

Use verify method to ensure a token is valid (decode is only there to read token props)
fix logout bug
fix #373

fix: verify token on handle / security

---

hasura/metadata/databases/carnet_de_bord/tables/public_professional.yaml

fix: update permision to filter pro using deploymentId

---

.github/workflows/preproduction.yml

preprod pipeline failed due to misconfiguration of e2e  (missing artifact)
cf  https://github.com/SocialGouv/carnet-de-bord/actions/runs/1559842054

ci: fix manifest name for e2e on preproduction pipeline

---

e2e/yarn.lock
yarn.lock

chore(deps): bump follow-redirects to 1.14.7 in ./ and e2e/

---

Dockerfile

Ceci permet de forcer un user non privilégié pour faire tourner le container docker
A quoi correspond le `node build` dans l'entrypoint à la fin Dockerfile ?
Ce serait aussi bien de supprimer les dépendances de dev de l'image finale, par ex avec un `yarn --production` après le build

fix(secu): use non-privilegied docker user

---

src/lib/graphql/_gen/typed-document-nodes.ts
src/lib/ui/ProNotebookMember/ProNotebookMemberView.svelte
src/routes/pro/carnet/_getNotebook.gql

Affichage de la date d'ajout d'un pro dans le détail du groupe de suivi.
Issue https://github.com/SocialGouv/carnet-de-bord/issues/596

feat: add created_at to notebook member detail

---

e2e/package.json
e2e/yarn.lock
package.json
yarn.lock

Run `npm audit fix`  ( https://stackoverflow.com/questions/51732435/is-there-a-yarn-alternative-for-npm-audit )
Some vulnerabilites cannot be fixed as they need to be fixed in codeceptjs first: https://github.com/codeceptjs/CodeceptJS/issues/3237

fix: update dependencies

---

hasura/migrations/carnet_de_bord/1645787372124_benef_struct_uniqueness/down.sql
hasura/migrations/carnet_de_bord/1645787372124_benef_struct_uniqueness/up.sql

fix: revert uniqueness on beneficiary_structure to exclude status

---

.pre-commit-config.yaml

Prettier essaie de changer le `changelog.md`, cette PR permet de le lancer que sur les fichiers JS/svelte/TS.

Exécution de prettier seulement sur le JS

---

src/routes/auth/__layout.svelte

j'ai regénéré un lien de partage depuis nextloud; le précédent n'avait plus l'air d'exister.
closes #819

fix: fix old video link

---

e2e/codecept.conf.js
e2e/step_definitions/downloads_helper.js
e2e/step_definitions/steps.js

Add a custom CodeceptJS helper to improve testing of downloads.
CodeceptJS's default Playwright helper:
- does not use the server's provided filename, preventing tests
from asserting its value;
- does not clear the output directory, allowing downloaded files
from a previous run or test to trigger a false positive;
- requires a target filename as its argument, otherwise it
downloads any file to an `output/downloads` file, which in
turn creates false positives because
`I.seeFile("output/downloads/file")` (wrongly) succeeds when `output/download`
exists as a file and not a directory.

ci: introduce helper to better handle downloads in e2e tests

---

src/routes/manager/professionnels/index.svelte

For pleasure of the eye.
Before: 
After:

refactor: add some spacing before Professionals table

---

src/lib/constants/keys.ts

Il arrive que les droits RSA ne soient pas renseignés. 
Cela a pour conséquence d'afficher `RSA - undefined` dans le carnet de bord.
cf. #1015 
Lorsque les droits ne sont pas renseignés, la colonne en base de données est renseignée à `NULL`.  
Pour afficher `RSA - Droit non renseigné`, on ajoute une valeur à la map `rsaRightKeys` (dans le fichier [src/lib/constants/keys.ts]())
RAS
1- Se connecter à carnet de bord
2- Dans la liste des bénéficiaires, choisir un bénéficiaire dont la donnée "droit RSA" est vide qui n'est pas assigné au compte utilisé  <img width="117" alt="non assigné" src="https://user-images.githubusercontent.com/2989532/188704136-5a8992f2-16ee-489b-9437-381bcbca8bf5.png">
Dans la section "Situation socioprofessionnelle", vérifier que s'affiche `RSA - Droit non renseigné`. …

fix: display that RSA is not defined when RSA rights are null

---

backend/api/db/crud/admin_structure.py
backend/api/v1/routers/admin_structures.py
backend/api/v1/routers/managers.py
backend/tests/api/test_admin_structures.py
src/lib/services/backend.ts
src/lib/ui/AdminStructure/AddAdminStructureLayer.svelte

ETQ gestionnaire de structure, ajouter des co-gestionnaires de structure DÉJA existants
J'ai modifié le endpoint `/admin_structure/create` pour qu'il verifie si l'admin à créer n'existe pas (en cherchant par email)
Si le pro n'existe pas, on fait comme avant (creation de l'admin structure + creation du compte + envoi de mail) puis création de la relation structure / admin structure
Si le pro existe, on ne crée alors que la relation structure / admin_structure
Les tests pytest ont été modifiés en conséquence
Si la relation admin_structure / structure existe déjà, il y aura une erreur lors de l'ajout
Se connecter en tant que jacques.celaire@livry-gargan.fr et aller sur la structure `Centre Communal d'action social Livry-Gargan`
Ajouter un gestionnaire
Saisir les informations suivantes …

fix: allow add existing admin to structure

---

e2e/features/manager/showListBeneficiairies.feature
e2e/features/manager/viewNotebook.feature
e2e/features/structureAdmin/viewNotebook.feature
e2e/step_definitions/steps.js
src/lib/graphql/_gen/typed-document-nodes.ts
src/lib/ui/BeneficiaryList/ListWithStructure.svelte
src/lib/ui/BeneficiaryList/_getBeneficiaries.gql

fixes #984 
En tant qu'admin, la date de naissance n'est pas directement accessible dans la liste des bénéficiaires (onglet "bénéficiaires"). 
Il faut, à chaque fois, entrer dans le carnet en lecture pour en prendre connaissance.
On ajoute une colonne date de naissance dans la liste des bénéficiaires.
RAS
Se connecter avec le compte `manager.cd93`.
Se rendre sur la liste des bénéficiaires (onglet "bénéficiaires").
Constater l'ajout de la colone `Date de naissance`.

feat: Ajoute la date de naissance dans la liste des bénéficiaires pour un admin.

---

e2e/features/manager/viewNotebook.feature
src/lib/ui/Beneficiary/SocioProView.svelte
src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProUpdate.svelte
src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProView.svelte

closes #1066 
La RQTH est une décision administrative permettant - entre d'autre - d'être concerné par l' "obligation d'emploi" des personnes handicapées incombant aux entreprises. 
Ce n'est pas une aide alors qu'aujourd'hui elle figure dans les "Droits" sur le carnet et peut être sélectionnée parmi les "Autres aides".
Déplacer la donnée RQTH sur le carnet pour : 
- qu'elle apparaisse à côté de la situation socioprofessionnelle
- qu'elle puisse être sélectionnable indépendamment des autres aides dans le volet latéral "Mettre à jour"
Quand la situation socioprofessionnelle n'est pas renseignée, la section concernant la donnée RQTH est affichée à gauche pour éviter un blanc (voir le gif).
Se connecter en tant que chargé d'orientation avec le compte 'giulia.diaby@cd93.fr'.
Affecter le …

feat: Extraire la donnée RQTH de la section des "Droits"

---

backend/api/db/models/notebook_member.py
hasura/seeds/carnet_de_bord/seed-data.sql

Lors de l'exécution du script d'export Vitamine, une erreur met en évidence un mauvais typage Python.
Modification du type Python et mise à jour des fixtures pour reproduire le souci.
`poetry run python scripts/export_notebook.py 1c52e5ad-e0b9-48b9-a490-105a4effaaea` devrait s'exécuter avec succès et produire un JSON sur stdout.

fix: correction du type de creator_id

---

backend/scripts/export_notebook.py
backend/scripts/parse_csv_pe.py

Actuellement les erreurs des scripts ne sont pas remontées dans Sentry.
Initialiser Sentry au début de l'appel du script.
Seuls les scripts `export_notebook.py` et `parse_csv_pe.py` sont appelés sur la production.
À discuter
fix #1085

fix: ajout de sentry aux scripts python

---

.github/workflows/lint.yml
.github/workflows/preproduction.yml
.github/workflows/test.yml

L'action https://github.com/c-hive/gha-yarn-cache utilisée pour configurer le cache Yarn est obsolète, son `README` recommande d'utiliser désormais l'action standard `actions/setup-node` avec son option `cache`.
Par ailleurs, sans certitude que ce soit lié, on a constaté récemment des instabilités dans l'exécution de cette action : https://github.com/SocialGouv/carnet-de-bord/actions/runs/3081279513/jobs/4979641913, https://github.com/SocialGouv/carnet-de-bord/actions/runs/3081186419/jobs/4979440620, https://github.com/SocialGouv/carnet-de-bord/actions/runs/3081179757/jobs/4979425383, https://github.com/SocialGouv/carnet-de-bord/actions/runs/3064367285/jobs/4947399309 .
De plus, on ne contrôle pas la version de NodeJS utilisée pour la compilation et les tests, étant ainsi dépendant de la …

ci: replace deprecated gha-yarn-cache with setup-node

---

e2e/features/manager/showListProfessionals.feature
src/lib/graphql/_gen/typed-document-nodes.ts
src/lib/ui/ProfessionalList/Container.svelte
src/lib/ui/ProfessionalList/Filters.svelte
src/lib/ui/ProfessionalList/List.svelte
src/lib/ui/ProfessionalList/_getProfessionalsForStructure.gql
src/routes/structures/[uuid]/index.svelte
src/routes/structures/[uuid]/professionnels.svelte

closes #902 
ETQ que gestionnaire de structure, je peux importer des professionnels.
Or, par la suite, je ne peux pas retrouver la liste des professionnels que j'ai importés sur l’outil.
Or l’accès à ces données est essentiel pour que je puisse comprendre / visualiser qui sont les professionnels affectés à la structure dont je suis en charge.
Ajout d'une page présentant la liste des professionnels d'une structure donnée, accessible à tout gestionnaire de structure.
Je n'ai pas utilisé exactement les mêmes couleurs que la maquette mais les couleurs `bg-information` et `text-information`.
Se rendre sur la review app : https://cdb-app-review-pr1089.osc-fr1.scalingo.io/.
Se connecter en tant que gestionnaire de structure avec le courriel `jacques.celaire@livry-gargan.fr`.
Choisir la structure …

feat: [Gestionnaire de structure] Afficher la liste des professionnels d'une structure.

---

e2e/features/manager/showListBeneficiairies.feature
e2e/features/manager/showListProfessionals.feature
e2e/features/manager/validateAccount.feature
package.json
src/lib/ui/BeneficiaryList/Container.svelte
src/lib/ui/BeneficiaryList/Filters.svelte
src/lib/ui/Dialog.svelte
src/lib/ui/LayerCDB.svelte
src/lib/ui/Pagination.svelte
src/lib/ui/ProfessionalList/List.svelte
src/routes/manager/beneficiaires/index.svelte
src/routes/manager/professionnels/index.svelte
src/routes/orientation/index.svelte
src/routes/structures/[uuid]/beneficiaires.svelte
yarn.lock

fix #769
En tant que manager, je souhaiterai pouvoir voir la liste des bénéficiaires rattachés à un pro
Créer un filtre pour voir les beneficiaire d'un pro. Pour cela j'ai rajouté un parametre d'url nommé   `member`  qui prend un email comme valeur.
Le filtre fonctionne pour des pro ou des chargé d'orientation
Se connecter en tant `manager.cd93`, cliquer sur le menu "Professionnel" puis cliquer sur la pastille contenant le nombre de bénéficiaires rattachés à un pro

feat: filter beneficiary list with a  notebook member

---

src/routes/auth/login/index.ts

fixes #1063
Lors de la connexion à Carnet de Bord, si l'utilisateur a saisie sans s'en rendre compte (par exemple via un copier / coller) des espaces avant et/ou après son courriel, celui-ci ne sera pas reconnu.
De prime abord, l'utilisateur peut penser que le service est temporairement en panne (cela m'est arrivé ...).
Côté backend, lors de la connexion, on commence par supprimer les espaces avant / après (via la fonction `trim()`).
J'ai tenté de mettre des tests `jest` et `testing-library` mais sans succès :(
A voir la direction que l'on souhaite prendre côté frontend et si cela vaut le coup d'investir du temps sur nos tests frontend.
Se rendre sur la review app : https://cdb-app-review-pr1101.osc-fr1.scalingo.io/.
Essayer de se connecter avec identifiant valide (ex. `manager.cd93`) …

fix: Ne pas considérer les espaces avant / après lors de la connexion.

---

.github/pull_request_template.md
.github/workflows/review-scalingo.yml

Chaque ouverture ou ré-ouverture de pull request entraîne la création de review apps sur Scalingo.
Il est possible d'y accéder en cliquant sur le bon _check_ dans la pull request.
Néanmoins, cela est peu pratique car il faut cliquer sur `show all checks`, puis chercher la bonne action et enfin cliquer sur `details` (et dans ce cas, on est redirigé sur la review app dans la même fenêtre, perdant au passage le contexte initial).
On met à jour automatiquement la description de la pull request avec l'adresse de la review app déployée, dans la section _Comment tester_.
Pour cela on utilise [l'action GitHub](https://github.com/blablacar/action-sticky-description) qui permet de remplacer un texte entre 2 balises par le texte de notre choix.
On met également à jour le modèle de pull request pour …

ci: Mise à jour automatique de la description d'une Pull Request avec l'adresse de la Review App.

---

backend/scripts/pe-fetch.sh

Notre job hebdomadaire de téléchargement des fichiers Pôle Emploi échoue lors du déchiffrement du fichier `actions` depuis que la taille de celui-ci a sensiblement augmenté (passant de 1 Go à 2 Go environ) lors de l'ajout de nouveaux départements (pour la première fois dans le fichier vu le 9 septembre 2022).
L'outil `openssl smime` comporte en effet une limitation qui empêche de traiter les fichiers qui approchent les 2 Go. Voir par exemple https://marc.info/?l=openssl-users&m=138545785012939 ou encore https://gist.github.com/gsilos/879c28279761cd8d38301f7a54bed78a .
Comme on n'utilise pas actuellement les données du fichier `actions`, nous désactivons provisoirement le téléchargement et le déchiffrement de ce fichier, en attendant d'obtenir la livraison d'un fichier exploitable. …

Import Pôle Emploi : ne plus essayer de déchiffrer le fichier `actions`

---

src/routes/manager/professionnels/index.svelte

Dans l'affichage de la liste des pros, on affiche dans la colonne onbarding les valeurs "Fait" / "Non fait" ou "Fait" / "Pas fait"
On choisi d'utiliser "Non fait"
ras
ouvrir les listes de pro dans les 2 profils (manager et admin_structure)
Se rendre sur la [review app](https://cdb-app-review-pr1107.osc-fr1.scalingo.io).

fix: use same wording on onboarding

---

hasura/migrations/carnet_de_bord/1663750758041_squashed/down.sql
hasura/migrations/carnet_de_bord/1663750758041_squashed/up.sql

La table wanted_job ne possède pas de colonne created_at / updated_at
Ajouter les colonnes à la table
ras
Récupérer la branche, et redémarrer hasura. lancer la console Hasura et vérifier que les colonnes existent. 
Se rendre sur la [review app](https://cdb-app-review-pr1106.osc-fr1.scalingo.io).

feat: add created_at / updated_at on wantedjob

---

.github/workflows/notification.yml
.github/workflows/production.yml

On met en production régulièrement et il est parfois compliqué de suivre le rythme et le contenu des déploiements côté produit.
On ajoute une étape d'envoi de message vers Mattermost à chaque succès du worklfow de déploiement en production.
Le webhook utilisé poste les messages dans le canal `~startup-carnetdebord-deploiments`, en incluant le contenu du CHANGELOG ajouté depuis le dernier déploiement en production.
A voir si cela convient à l'usage.
Un premier test a été fait en exécutant l'action GitHub :

ci: add a notification on Mattermost

---

README.md
app/src/routes/index.svelte
e2e/features/home.feature

closes #1112
Actuellement, la page d'accueil affiche un texte de bienvenue faisant mention d'une nouvelle version en ligne (sic).
Une nouvelle version étant effectivement prévue et parfois mentionnée aux différents acteurs du produit, cela porte à confusion.
Remplacer *"La nouvelle version du Carnet de bord est en ligne !"* par *Bienvenue sur Carnet de bord !*.
On en profite également pour corriger la typo (le `s` en trop à `entre`) dans la page d'acceuil.
La même typo existait également dans le `README`, on en profite pour corriger cette faute également.
Se rendre sur la [review app](https://cdb-app-review-pr1123.osc-fr1.scalingo.io).
Vérifier que le texte affiché est *Bienvenue sur Carnet de bord !*.

Mise à jour du texte de bienvenue de la page d'accueil.

---

.github/actions/hasura-cli/action.yml
.github/workflows/lint.yml
.github/workflows/test.yml
INSTALL.md
hasura/Dockerfile

L'image docker d'hasura utilisé actuellement contient à la fois les composant open source et closed source et est en retard de version. 
Depuis la version 2.12, Hasura met à disposition une image avec seulement les composants opensource. Cela permettrait d'alléger l'image finale. Afin de pouvoir bénéficier des dernieres fonctionnalité ainsi que les corrections de bug,  on souhaite avoir des mises à jour régulière.
mettre à jour le nom de l'image utilisée avec le prefix `-ce`  
Si tests e2e passent on peut être confiant dans le bon fonctionnement de l'appli
Se rendre sur la [review app](https://cdb-app-review-pr1113.osc-fr1.scalingo.io).

chore: use hasura 2.12-ce image

---

app/.eslintrc.cjs
app/src/global.d.ts
app/src/lib/ui/base/Footer.svelte
app/svelte.config.js

Il est compliqué aujourd'hui pour un utilisateur lambda de connaitre la version de l'application client actuellement utilisée.
Cela est pourtant une donnée clé pour comprendre / analyser les rapports de bogues ou demandes d'évolutions.
On ajoute la version dans le pied de page de l'application client.
Celle-ci est lue depuis le fichier `package.json` afin de garantir sa cohérence.
On en profite pour faire de ce numéro de version un lien vers le fichier `CHANGELOG.md` permettant aux utilisateurs curieux de s'informer des changements.
Voir la documentation de [Vite](https://vitejs.dev/config/shared-options.html#define) pour comprendre comment rendre disponible une variable globale.
Se rendre sur la [review app](https://cdb-app-review-pr1135.osc-fr1.scalingo.io/).
Vérifier que le pied de …

feat: Ajout du numéro de version dans le pied de page de l'application.

---

backend/cdb_csv/pe.py
backend/tests/test_pe_csv_import.py

Lorsqu'une exception est lancée dans le code d'import PE pour une ligne donnée le script plante et les autres lignes ne sont pas traitées.
Capturer les exceptions lancées lors de l'analyse de chaque ligne du CSV.
Toutes les exceptions sont capturées avec un _catch all_
Difficile à tester en dehors de la production.
Lors du prochain import pôle emploi, s'assurer que toutes les lignes ont bien été traitées.
fix #1128

fix: catch des exceptions lancées à chaque parsing de ligne CSV

---

.github/workflows/test.yml
.gitignore
backend/README.md
backend/poetry.lock
backend/pyproject.toml

Lors du développement (spécialement en TDD), il est pratique de lancer les tests en mode `watch` afin d'avoir une vue toujours à jour des test.
Il est actuellement possible de le faire sur les tests backend avec `pytest-watch` mais chaque changement de code relance l'intégralité des tests.
L'exécution de la suite de tests au complet étant longue, cela donne une boucle de rétro-action longue et peu efficace lors du cycle Rouge Vert Refactor.
En ajoutant la dépendance `pytest-testmon`, il est possible de ne lancer que les tests liés aux changements de code.
La documentation a été mise à jour, voir [./backend/README.md]().
On en profite pour déplacer les dépendances liées aux tests dans les `dev-dependencies`.
La version de `python` a du être restreinte à `<3.12` afin de pouvoir résoudre …

chore: Ajout de pytest-testmon pour ne lancer que les tests liés aux changements de code.

---

hasura/migrations/carnet_de_bord/1665481676818_remove-rqth/down.sql
hasura/migrations/carnet_de_bord/1665481676818_remove-rqth/up.sql

la situation RQTH de l'axe de travail `Emploi` est en doublons avec la situation socio-professionnelle
on supprime RQTH des situations de l'axe "Emploi" et on le supprime des situations existantes
Est ce que pour les carnets avec une situation RQTH on doit aussi ajouter RQTH dans la situations socio pro ?  
Se rendre sur la [review app](https://cdb-app-review-pr1163.osc-fr1.scalingo.io).

feat(data): remove rqth from situations

---

backend/scripts/pe-fetch.sh

le script `pe-fetch` récupère la dernière version du fichier. pour cela on exécute une commande et on place le résultat dans une variable. Le nom de la variable était préfixé inutilement d'un `$`. 
suppression du caractère en trop.
Il va falloir lancer le script manuellement et valider qu'il prend bien en compte le dernier fichier
fix #1162 
Se rendre sur la [review app](https://cdb-app-review-pr1176.osc-fr1.scalingo.io).

fix(data): recupération correcte du dernier fichier PE

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/ui/Manager/_importStructure.gql
app/src/lib/ui/ProNotebookMember/ProNotebookMemberInvitation.svelte
app/src/lib/ui/ProNotebookMember/_SearchProfessional.gql
app/src/lib/ui/ProfessionalList/_getProfessionalsForStructure.gql
app/src/lib/ui/StructureEdit/updateStructure.gql
app/src/routes/actions/_insertStructure.gql
backend/api/core/emails.py
backend/api/core/exceptions.py
backend/api/core/sendmail.py
backend/api/db/crud/account.py
backend/api/db/crud/admin_structure.py
backend/api/db/crud/manager.py
backend/api/db/crud/orientation_manager.py
backend/api/db/models/account.py
backend/api/db/models/structure.py
backend/api/v1/main.py
backend/api/v1/routers/admin_structures.py
backend/api/v1/routers/managers.py
backend/api/v1/routers/structures.py
backend/api/v1/routers/uploads.py
backend/tests/api/test_admin_structures.py
backend/tests/api/test_csv2json.py
backend/tests/api/test_managers.py
backend/tests/api/test_structures.py
backend/tests/api/test_uploads.py
backend/tests/conftest.py
hasura/metadata/actions.graphql
hasura/migrations/carnet_de_bord/1664790703990_alter_table_public_structure_alter_column_name/down.sql
hasura/migrations/carnet_de_bord/1664790703990_alter_table_public_structure_alter_column_name/up.sql

Actuellement l'import des structures est réalisé coté front, sans que les données soient validés / pré-traité, ce qui peut entraînait des problèmes de structure en double.
Stocker les données dans la base avec un champ non sensible à la casse. 
Passer l'import coté backend et améliorer le pré-traitement des données.
On profites de la PR pour uniformiser les pratiques (
- généralisation des return None dans les crud plutot que des `raise Error()`
- utilisation de `@mock.patch` pour simplifier l'écriture des tests
- utilisation de classe dédié pour les exceptions
- refactor du code lié à l'envoi de mail
- fix des requetes graphql (searchProfessionnal utilisant une variable `search:String` or pour hasura citext n'est pas compatible avec String)
- 
Récupérer la branche et lancer le backend. …

feat(backend):  import structures endpoint

---

.pre-commit-config.yaml

Le fichier de types `app/src/lib/graphql/_gen/typed-document-nodes.ts` est généré en utilisant la commande `yarn —cwd app codegen`.
Actuellement le fichier est versionné avec le code dans le git.
Cela pose parfois des soucis car un changement dans les queries ou mutations (par exemple en changeant un fichier `.gql`) n’entraine pas une re-génération du fichier de types.
Afin de garantir que le fichier généré est à jour, on ajoute un hook de precommit qui échoue si le fichier de sortie `typed-document-nodes` est plus ancien que l'ensemble des fichiers `*.gql`.
RAS
Modifier un fichier `*.gql`.
Essayer de le commiter **sans générer** les types auparavant.
Vérifier que le hook de precommit `check-codegen` échoue.
Se rendre sur la [review app](https://cdb-app-review-pr1177.osc-fr1.scalingo.io).

chore: Ajout d'un precommit hook pour assurer la fraîcheur de la génération `codegen`

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/routes/manager/_getDeploymentInfo.gql
app/src/routes/manager/index.svelte
app/src/routes/structures/[uuid]/index.svelte
e2e/features/manager/home.feature
e2e/features/manager/rattachement.feature

closes #1073
Lorsqu'un gestionnaire de structure rattache un bénéficiaire à un professionnel, les indicateurs de l'accueil ne sont pas mis à jour tant que la page n'est pas rafraichie.
Lorsqu'un manager importe des bénéficiaires, les indicateurs de l'accueil ne sont pas mis à jour tant que la page n'est pas rafraichie.
On ajoute les `additionalTypenames` à la requête `GetStructure` pour forcer un rechargement du cache lorsque des données de type  `beneficiary_structure` et `notebook_member` sont mises à jour.
Plus d'informations dans la [documentation de `urql`](https://formidable.com/open-source/urql/docs/basics/document-caching/).
On fait la même chose pour la requête `GetDeploymentInfos` afin que les indicateurs du manager soient mis à jour après l'import de bénéficiaires.
Pour …

fix: Mettre à jour les indicateurs de l'accueil après une action / un import.

---

.releaserc
INSTALL.md

On a migré le gestionnaire de dépendence de l'application `svelte` de `yarn` vers `npm`.
Dans cette migration on a oublié de mettre à jour la création des releases.
Adapter la commande de création de la release (dans le fichier `.releaserc`).
Ajouter le fichier `package-lock.json` dans les fichiers à commiter lors de la création d'une release car ce fichier contient le numéron de version de l'application.
Au passage, on en profite pour mettre à jour les dernières mentions de l'usage de `yarn` dans la documentation.
Se rendre sur la [review app](https://cdb-app-review-pr1205.osc-fr1.scalingo.io).

chore: Utiliser `npm` pour créer les versions.

---

app/src/routes/+layout.svelte

Actuellement lors du chargement de l'application on a une erreur dans la console du navigateur :
```
Refused to load data:application/manifest+json;base64,ewogICAgImljb25zIjogWwogICAgICAgIHsKICAgICAgICAgICAgInNyYyI6ICJhbmRyb2lkLWNocm9tZS0xOTJ4MTkyLnBuZyIsCiAgICAgICAgICAgICJzaXplcyI6ICIxOTJ4MTkyIiwKICAgICAgICAgICAgInR5cGUiOiAiaW1hZ2UvcG5nIgogICAgICAgIH0sCiAgICAgICAgewogICAgICAgICAgICAic3JjIjogImFuZHJvaWQtY2hyb21lLTUxMng1MTIucG5nIiwKICAgICAgICAgICAgInNpemVzIjogIjUxMng1MTIiLAogICAgICAgICAgICAidHlwZSI6ICJpbWFnZS9wbmciCiAgICAgICAgfQogICAgXQp9Cg== because it appears in neither the manifest-src directive nor the default-src directive of the Content Security Policy.
content.js:328
```
Qui nous indique donc que le `webmanifest` déclaré par l'application n'est pas chargé car en violation de la …

fix: supprime la référence invalide à un webmanifest

---

app/elm.json
app/svelte.config.js

Le support par clavardage n'est plus opérationnel sur l'environnement de préproduction.
Avant on n'avait pas de `script-src` donc on retombait sur `default-src` qui autorise bien ``*.crisp.chat`.
Avec la PR sur le tooling ELM, on a désormais un `script-src` vide en production (et juste `unsafe-eval` en dev) et donc crisp.chat ne se charge plus.
Dans la configuration `svelte`, on autorise les scripts dont l'origine est une valeur comprise parmis celles autorisées pour le `default-src`.
On profite de la PR pour passer prettier sur le fichier `elm.json`.
Se rendre sur la [review app](https://cdb-app-review-pr1213.osc-fr1.scalingo.io).
Vérifier que le support par clavardage est opérationnel.

fix: Restauration du support des scripts permettant le support par clavardage (crisp).

---

app/src/lib/ui/Manager/ImportBeneficiaries.svelte

Le NIR n'apparait pas dans les données validées lors de l'import bénéficiaire.
Ajout d'une ligne NIR dans l'écran de validation.
Lors de l'import bénéficiaire du département, le NIR apparait dans les données validées avant de confirmer l'import.
Se rendre sur la [review app](https://cdb-app-review-pr1218.osc-fr1.scalingo.io).

feat: add nir to validation report during beneficiary import

---

app/src/lib/emailing/emails.ts
app/src/routes/(public)/inscription/+page.svelte

Voir #1215 :
> La https://github.com/gip-inclusion/carnet-de-bord/issues/814 a permis de mieux identifier d'où provient la demande de création de compte reçue par le manager d'un territoire. Néanmoins, ce mail continue de faire naître des incompréhensions / de la confusion chez les manager car l'action qui est attendue d'eux n'est pas claire.
On enrichit le texte du courriel pour préciser pourquoi ce courriel est reçu et quelle est l'action attendue :
>  <img width="858" alt="image" src="https://user-images.githubusercontent.com/300823/199542646-f9bc3838-b3ca-4645-aadb-590b5cc823b0.png">
Le message de confirmation affiché à la personne qui demande son inscription a aussi été enrichi pour préciser qu'un courriel de confirmation ne sera reçu que si sa demande est validée.
> <img …

feat: Préciser l'action attendue dans le mail de notification de demande de création de compte

---

.github/workflows/release.yml
DEPLOY.md
INSTALL.md
app/package.json
app/src/lib/ui/base/Footer.svelte
e2e/package.json
scripts/create-review-apps.sh

Le workflow de release ne tourne plus suite au déménagement du repo dans l'organisation `gip-inclusion`.
Le workflow `release.yml` passait à l'action `semantic-release` un token GitHub (nécessaire pour pousser le commit de release dans le repo) trouvé dans un secret nommé `SOCIALGROOVYBOT_BOTO_PAT`, or ce secret était hérité de l'organisation `SocialGouv`.
Pour débloquer la création de release dans un premier temps, nous avons créé un secret de ce même nom au niveau de ce repo, mais dans cette PR on renomme le secret `SEMANTIC_RELEASE_GITHUB_TOKEN`.
Cette PR met également à jour les références restantes à `SocialGouv/carnet-de-bord`.

ci: Ne plus dépendre d'un token de `SocialGouv` pour la création de release

---

app/src/routes/auth/+layout.svelte
app/src/routes/auth/jwt/[uuid]/+error.svelte
app/src/routes/auth/jwt/[uuid]/+page.server.ts
app/src/routes/auth/jwt/[uuid]/+page.svelte
app/src/routes/auth/login/+layout.svelte
app/src/routes/auth/logout/+server.ts
scripts/launch_tests.sh

Certains utilisateurs, en cliquant sur le lien de connexion reçu par courriel, ne sont pas correctement authentifiés et arrivent sur la page d'accueil non connecté.
Après analyse, il s'avère que le cookie qui est installé par la réponse à `/auth/jwt/[uuid]` dans le cadre d'une réponse de redirection (302), n'est pas toujours immédiatement renvoyé par le navigateur lorsque celui-ci suit la redirection (peut-être une manifestation de https://bugs.chromium.org/p/chromium/issues/detail?id=696204 par exemple), en particulier quand la requête initiale est _cross-site_, ce qui est généralement le cas quand le lien a été cliqué dans un Webmail.
Pour éviter cette situation, avec cette PR on change la route `/auth/jwt/[uuid]` pour faire une réponse normale (200), et la redirection est faite dans le …

fix: redirection après connexion

---

e2e/codecept.conf.js
e2e/step_definitions/steps.js
scripts/launch_tests.sh

Depuis la mise à jour Svelte, les tests end-to-end (CodeceptJS) sont instables.
On constate que CodeceptJS retente parfois la navigation vers la page `/auth/jwt/[uuid]`, or le code fourni dans cette URL ne peut être utilisé qu'une seule fois, ce qui fait échouer le test.
Après analyse il s'avère que l'échec de l'étape `I.amOnPage` est causé par une tentative d'exécuter un script dans la page après navigation pour collecter des statistiques de performances : https://github.com/codeceptjs/CodeceptJS/blob/37d1dc47029aea8294eef161b75a7e8f2f49d4a1/lib/helper/Playwright.js#L822
Cette exécution échoue quand elle intervient après la navigation déclenchée automatiquement par la page `/auth/jwt/[uuid]` depuis #1225.
On évite d'utiliser `I.amOnPage` pour cette navigation, en utilisant directement …

ci: Corriger l'étape de login dans les tests e2e

---

.releaserc

Les règles de création de release actuellement appliquées par `semantic-release` ne déclenchent pas la création de release quand on intègre des changements qui ne sont pas marqués `fix` ou `feat`. Par conséquent, ces changements ne sont pas automatiquement déployés en pré-production, alors qu'ils peuvent souvent avoir un intérêt à être testés puis déployés en production.
Bien sûr, en théorie un changement qui n'est pas censé avoir d'impact visible sur le produit (donc qui n'est pas marqué `feat` ni `fix`) n'a pas besoin d'être déployé indépendamment, mais dans la pratique on constate souvent que ce qui est pour l'essentiel un _refactoring_ dans l'intention, intègre des impacts mineurs comme des corrections de fautes de frappe, etc.
On modifie les règles de création de release (cf. …

ci: création d'une release à chaque merge sur master

---

backend/api/db/crud/beneficiary.py
backend/api/db/models/beneficiary.py
backend/cdb_csv/pe.py
backend/tests/test_pe_csv_import.py
hasura/metadata/databases/carnet_de_bord/tables/public_beneficiary.yaml
hasura/migrations/carnet_de_bord/1669048458209_alter_table_public_beneficiary_add_column_pe_unique_id/down.sql
hasura/migrations/carnet_de_bord/1669048458209_alter_table_public_beneficiary_add_column_pe_unique_id/up.sql

Lors de l'import du fichier PE principal, nous ne gardons pas le champ nommé `identifiant_unique_de` qui représente un identifiant unique par bénéficiaire généré par PE. Cet identifiant permettant de trouver l'action correspondante dans le fichier des actions, nous ne sommes pour l'instant pas capable de faire le lien entre une action PE et le bénéficiaire lors de l'import.
Sauvegarder l'information `identifiant_unique_de` dans CdB lors de l'import du fichier principal de PE. Pour ce faire, on rajoute un champ `pe_unique_id` dans la table `Beneficiary`.
Les tests fonctionnels couvrent les cas de test
Se rendre sur la [review app](https://cdb-app-review-pr1277.osc-fr1.scalingo.io).
fix #1268

feat: stockage de l'identifiant unique Pôle Emploi lors de l'import

---

app/src/lib/ui/Beneficiary/SocioProView.svelte
app/src/lib/ui/Manager/ImportBeneficiaries.svelte
backend/api/db/models/beneficiary.py
backend/api/v1/routers/csv2json.py

fix #1279
La prévisualisation d'un fichier d'import de bénéficiaire n'affiche pas la colonne `Identidfant Pôle emploi` ni `Emploi recherché`. On affiche aussi la valeur des champs boolean au lien de Oui / Non 
Rajouter les colonnes manquantes et permettre d'afficher les valeur boolean en francais
On profite de la PR pour fixer un oubli lors de la correction de l'affichage de la Prime d'activité qui s'affiche `Bonus`  
Se rendre sur la [review app](https://cdb-app-review-pr1284.osc-fr1.scalingo.io).
Se connecter en tant `manager.cd93` et importer le fichier de beneficiaire suivant [Fichier import intial.xlsx](https://github.com/gip-inclusion/carnet-de-bord/files/10071205/Fichier.import.intial.xlsx). 
On observe bien le que les champs `Identifiant Pôle emploi` et `Emploi recherché` ainsi …

fix: add missing fields in import preview

---

.github/workflows/review.yml

Les PR ouvertes depuis d'autres repos que celui-ci déclenchent le _workflow_ de création de _review app_, mais celui-ci ne peut pas réussir car il s'exécute sans accès aux secrets nécessaires. En particulier, les PR ouvertes par Dependabot sont concernées, ex. #1275.
Pour des raisons de sécurité, on ne veut pas donner aux PR étrangères l'accès aux secrets. On se contente ici de désactiver la création de _review app_ dans le cas d'une PR venant d'un autre repo, ce qui nous évite d'avoir un échec qui apparaît dans la liste des exécutions.
Dans l'absolu des _review apps_ pourraient être intéressantes pour les PR de Dependabot, et on pourrait configurer le _workflow_ pour leur donner accès aux secrets, mais il y a une bonne raison pour laquelle GitHub a fait ce choix de ne pas donner accès …

ci: désactiver la création de review apps sur les PR étrangères

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/utils/post.ts
app/src/routes/auth/login/+page.svelte
app/src/routes/auth/login/+server.ts
app/src/routes/auth/login/_getAccountByUsernameorEmail.gql

close #1142
les messages d'erreurs au login sont peu informatifs si on a un compte inexistant ou un compte non confirmé
On différencie les messages d'erreur
On a crée une classe HTTPError pour récupérer le status / statusText
se connecter avec `bienvenu.lejeune` et voir le message d'erreur
se connecter avec `xyz.unknonw` et voir le message d'erreur
Se rendre sur la [review app](https://cdb-app-review-pr1298.osc-fr1.scalingo.io).

fix: améliorer les messages d'erreur de connexion

---

app/src/lib/ui/Beneficiary/SocioProView.svelte
app/src/lib/ui/BeneficiaryList/AddOrientationForm.svelte
app/src/lib/ui/BeneficiaryList/AddOrientationManagerForm.svelte
app/src/lib/ui/BeneficiaryList/AddProfessionnalForm.svelte
app/src/lib/ui/BeneficiaryList/AddStructureProfessionnalForm.svelte
app/src/lib/ui/BeneficiaryList/FilterOrientation.svelte
app/src/lib/ui/Manager/ImportBeneficiaries.svelte
app/src/lib/ui/Manager/errorMessage.ts
app/src/lib/ui/ProNotebookFocus/ProNotebookFocusCreate.svelte
app/src/lib/ui/ProNotebookMember/ProAppointment.svelte
app/src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProROME.svelte
app/src/lib/ui/format.ts
app/src/routes/+page.svelte
backend/api/db/crud/account.py
backend/api/db/crud/beneficiary.py
backend/api/db/crud/notebook.py
backend/api/db/models/beneficiary.py
backend/api/db/models/validator.py
backend/api/v1/routers/beneficiaries.py
backend/api/v1/routers/csv2json.py
backend/api/v1/routers/uploads.py
backend/tests/api/test_admin_structures.py
backend/tests/api/test_import_beneficiaries.py
backend/tests/conftest.py
backend/tests/test_beneficiary.py
backend/tests/test_beneficiary_import.py
e2e/features/manager/importBeneficiaires.feature

Actuellement, la mise à jour via import peut entrainer une perte d'information du bénéficiaire ou dans son carnet.
On met à jour seulement les champs dont la valeur n'est pas `None`
On a choisi cette solution car potentiellement moins soumise au risque perte de données. L'inconvénient est qu'on ne peut plus "vider" un champs via un ré-import. (Selon les retours, on aura la possibilité d'utiliser une valeur dédié à la remise à zéro d'un champ)
Afin que tout cela fonctionne, on a du modifier l'insert pour supporter None dans les champs boolean `right_are`, `right_rtqh`, `right_ass`, `right_bonus` car un Pre traitement du model pydantic passait les champs à False ce qui faisait que meme lorsque la valeur n'etait pas fourni (None) celle la etait transformé en False et donc sujet à …

fix: Ré-import partiel de bénéficiaires

---

app/src/lib/ui/AdminCreate/AdminCreate.svelte
app/src/routes/(auth)/manager/bienvenue/+page.svelte
app/src/routes/(auth)/orientation/beneficiaires/+page.svelte
e2e/features/manager/onboardingManager.feature
e2e/features/orientationManager/addOrientationManager.feature
e2e/features/orientationManager/filterBeneficiary.feature
e2e/features/orientationManager/orientationRequestsList.feature
e2e/features/orientationManager/rattachement.feature

Lors de la démo du sprint 22 (21/11/2022), nous avons relevé des messages, titre ou intitulés de champs peu clairs ou obsolètes.
Ca complique l'UX.
Afin de faciliter l'ergonomie / navigation, il faudrait modifier les textes suivants :
- (titre h1 de page) dans la page qui liste les bénéficiaires, il faudrait renommer le titre "Orientation des bénéficiaires" en "Bénéficiaires"
- (libellé) renommer "Admin PDI" en "Admin territoire"
Dans l'issue #1278, il est fait mention d'un message d'erreur à corriger.
Cela a été fait dans une autre PR, [déjà mergée](https://github.com/gip-inclusion/carnet-de-bord/blame/3c71e6c03550f086f0ee176ee31e2266159817ec/backend/api/v1/routers/beneficiaries.py)
Se rendre sur la [review app](https://cdb-app-review-pr1307.osc-fr1.scalingo.io).
closes #1278

chore: Changer des textes pour améliorer la navigation / lecture

---

INSTALL.md
backend/.buildpacks
backend/.slugignore

La version de Poetry utilisée lors des déploiements sur Scalingo (1.1.13) n'est plus celle qui est utilisée en test et développement (1.2).
On met à jour l'URL du _buildpack_ Poetry utilisé lors du déploiement pour utiliser la dernière version, qui permet d'installer une version plus récente de Poetry sélectionnée avec la variable `POETRY_VERSION`.
Pour contrôler les changements intervenus dans le buildpack : https://github.com/moneymeets/python-poetry-buildpack/compare/868d88bd7a4b11e62d57dbf673394ebf38962857..7bb05505bb21d56e6434417a7f649b40978fc705
Pour contourner des problèmes mineurs de compatibilité du _buildpack_ avec Scalingo (celui-ci étant prévu pour Heroku), un _fork_ du _buildpack_ a été créé : https://github.com/jonathanperret/scalingo-python-poetry-buildpack, c'est donc …

ci(scalingo): mise à jour du buildpack Poetry pour installer Poetry 1.2

---

app/src/lib/ui/OrientationRequest/ProOrientationRequestBanner.svelte

Dans le bandeau de réorientation pour les carnets consultés par des pros, la date affichée est toujours la date de demande, même quand une décision a été prise.
Afficher la date de décision si une décision a été prise.
En se connectant avec Paul Camara, vérifier que la date de demande d'acceptation de réorientation dans le profil de Janie Herring est le 3 septembre 2022.
Ne pas supprimer ce bloc, qui sera mis à jour [automatiquement](.github/workflows/review-scalingo.yml).

fix: date shown on reorientation decision banner

---

app/src/routes/(auth)/pro/carnet/[uuid]/+page.svelte

Lors de l'import des actions PE, aucune structure n'est affichée.
Afficher « Pôle Emploi » comme structure pour chaque évènement importé de Pôle Emploi.
Dans l'historique de parcours, les actions PE importées par le script devraient afficher comme structure « Pôle Emploi »
Se rendre sur la [review app](https://cdb-app-review-pr1330.osc-fr1.scalingo.io).
#755

fix: display Pôle Emploi structure for PE events

---

.env.sample
backend/api/core/logging.py
backend/api/core/sendmail.py
backend/api/core/settings.py
backend/api/db/crud/orientation_manager.py
backend/api/db/models/structure.py
backend/api/main.py
backend/api/v1/routers/admin_structures.py
backend/api/v1/routers/csv2json.py
backend/api/v1/routers/managers.py
backend/api/v1/routers/structures.py
backend/api/v1/routers/uploads.py
backend/poetry.lock
backend/pyproject.toml

Les logs de l'application backend ne sont pas au format JSON.
Cela n'est pas pratique à manipuler avec des scripts ou outils de gestion des logs.
On utilise `structlog` comme indiqué dans ce [gist](https://gist.github.com/nymous/f138c7f06062b7c43c060bf03759c29e).
Avec la variable d'environnement `LOG_AS_JSON` on peut choisir si on veut des logs au format JSON ou non.
Par défaut, on considère que oui (pratique pour tous les environements de déploiement actuels).
En local, on peut décider que non via le fichier `.env` (le fichier `.env.sample` a été mis à jour).
Chaque requête http fait désormais l'objet d'un log.
Pour conserver le comportement actuel des `logging.error` qui envoie l'erreur à Sentry, nous avons ajouté `structlog_sentry`.
Faire un appel http à l'API.
Vérifier dans les logs …

chore: Ajout d'un logger JSON dans l'application backend.

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/ui/BeneficiaryList/_getBeneficiaries.gql
app/src/routes/(auth)/orientation/demandes/_getBeneficiariesWithOrientationRequest.gql

Lors d'un rattachement après une orientation / réorientation (avec ou sans demande), la structure de rattachement affichée dans la liste des bénéficiaires n'est pas la nouvelle structure mais toujours l'ancienne.
Lors d'un changement d'orientation, on ne supprime pas la ligne `beneficiary_structure` mais on la modifie avec le statut `outdated` puis on en crée une nouvelle pour modéliser le rattachement à la nouvelle structure.
Lors de l'affichage de la liste des bénéficiaires, on ne filtre pas les structures mais le code assume que la première structure est la bonne et donc affiche toujours la toute première structure de rattachement du bénéficiaire.
Pour corriger ce comportement, on ajoute un filtre sur le statut pour exclure les `beneficiary_structure` dont le statut est `outdated`.
On …

fix: Afficher la nouvelle structure de rattachement dans la liste des bénéficiaires.

---

app/src/routes/(auth)/pro/annuaire/+page.svelte
app/src/routes/(auth)/pro/annuaire/+page.ts

Si un professionnel authentifié essaie d'accéder à la page de l'annuaire des bénéficiaires directement via son adresse (URL), la page échoue à se charger et une erreur est affichée.
Après investigation, on se rend compte que dans le cas d'un premier chargement, le `connectedUser` récupéré dans `pro/+page.ts` est `undefined`.
La tentative d'accès à l'id via une destructuration lève alors une exception `cannot destrcture id of undefined ...`.
Il n'y a pas d'intérêt particulier à récupérer l'identifiant de l'utilisateur authentifié puis de le passer en contexte de la page.
On peut utiliser directement le store `accountData` depuis la page svelte et ainsi bénéficier du mécanisme de mise à jour lors de la mise à jour du store.
RAS
Se connecter sur …

fix: Accéder à l'annuaire directement depuis son URL entraine une erreur.

---

app/src/hooks.server.ts
app/src/lib/ui/OrientationRequest/ChangeOrientationForm.svelte
app/src/lib/ui/OrientationRequest/DenyOrientationRequestConfirmation.svelte
app/src/lib/utils/post.ts
app/src/lib/utils/sentry.ts

Quand un serveur appelé par l'application Svelte renvoyait une erreur au format JSON, si le JSON ne contenait pas de propriété `message` on tentait de récupérer le texte de la réponse comme message d'erreur. Mais il est interdit dans l'API `fetch` d'appeler `response.text()` après avoir appelé `response.json()`.
Si la réponse est de type `application/json` on récupère son contenu avec `json()` puis si on ne trouve pas de propriété `message` (ni `detail`, qui est utilisé par défaut par FastAPI) on re-convertit tout le JSON en chaîne.
On ajoute aussi une capture d'exception via Sentry.
Faire une opération qui déclenche une réponse d'erreur. Par exemple (actuellement et jusqu'à ce que ce bug soit corrigé), tenter une réorientation quand on est connecté en tant qu'administrateur de structure …

fix(errors): meilleur traitement des réponses d'erreur JSON

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/ui/BeneficiaryList/ProSearchResults.svelte
app/src/lib/ui/ProBeneficiarySearchBar.svelte
app/src/routes/(auth)/pro/+layout.svelte
app/src/routes/(auth)/pro/annuaire/+page.svelte
app/src/routes/(auth)/pro/annuaire/+page.ts
app/src/routes/(auth)/pro/annuaire/_searchPublicNotebooks.gql
app/src/routes/+layout.server.ts
e2e/features/pro/annuaire/recherche.feature
hasura/metadata/databases/carnet_de_bord/functions/functions.yaml
hasura/metadata/databases/carnet_de_bord/functions/public_search_public_notebooks.yaml
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_public_view.yaml
hasura/migrations/carnet_de_bord/1671012020468_search_public_notebooks/down.sql
hasura/migrations/carnet_de_bord/1671012020468_search_public_notebooks/up.sql

Depuis l'annuaire un pro accède uniquement à l'annuaire de ses bénéficiaires la barre de recherche de l'écran d'accueil ne lui permet pas de voir ceux dont il n'est pas dans le groupe de suivi
Permettre aux profils professional de rechercher, et d'accéder au carnet de bord de n'importe quel bénéficiaire uniquement en lecture.
Pour ce faire on change la requête graphql qui interrogeait les `notebook_member` pour la faire interroger la nouvelle vue contentant les `public_notebook`.
On cherche maintenant dans les prénoms ET les noms
Se connecter en tant que `pierre.chevalier`, chercher dans l'annuaire des bénéficiaires 'myrna' et s'assurer que son notebook s'affiche bien dans les résultats de recherche.
Se rendre sur la [review app](https://cdb-app-review-pr1360.osc-fr1.scalingo.io).
fix …

feat: autoriser la recherche de tous les notebooks

---

hasura/migrations/carnet_de_bord/1671553444065_migrate_pending_and_done_beneficiary_structures/down.sql
hasura/migrations/carnet_de_bord/1671553444065_migrate_pending_and_done_beneficiary_structures/up.sql

Il reste des `beneficiary_structure` avec le statut `done` ou `pending`.
Changer le default pour la colonne `status`, et migrer les données.
Tester la migration en local.
Se rendre sur la [review app](https://cdb-app-review-pr1369.osc-fr1.scalingo.io).

feat: get rid of 'default' and 'done' definitely

---

app/src/lib/ui/AdminStructure/AdminStructureForm.svelte
app/src/lib/ui/AdminStructure/adminStructure.schema.test.ts
app/src/lib/ui/AdminStructure/adminStructure.schema.ts
app/src/lib/ui/ProBeneficiaryUpdate/beneficiary.schema.ts
app/src/lib/ui/StructureEdit/StructureCreationForm.svelte
app/src/lib/ui/StructureEdit/structure.schema.test.ts
app/src/lib/ui/StructureEdit/structure.schema.ts
app/src/lib/validation.test.ts
app/src/lib/validation.ts
backend/api/db/crud/structure.py
backend/api/db/models/structure.py
backend/api/v1/routers/structures.py
backend/tests/test_structure.py

Certaines structures ne sont pas importés parce qu'elle contienne des champs email vide dans la base ce qui leve une exception car le model Pydantic actuel s'attend à trouver des adresses email valide.
Modifier les modèles pydantic et éviter d'enregistrer des chaines vides depuis le client.
Se rendre sur la [review app](https://cdb-app-review-pr1374.osc-fr1.scalingo.io).
fix  #1373

fix: update python structure model and transform empty string to null

---

app/src/lib/ui/BeneficiaryList/ProSearchResults.svelte
e2e/features/pro/carnet/read_only_other_notebook.feature

ETQ Pro, quand j'effectue une recherche d'usagers depuis la page annuaire des bénéficiaires et que je cherches à accéder à un carnet depuis les résultats de cette recherche, j'arrive sur une page qui n'existe pas. il y a une erreur dans l'url (un s en trop à carnet)
On met à jour le lien avec la bonne url
on en profite pour mettre à jour le test d'acces au carnet anonyme pour avoir un parcours complet
- Se connecter en tant que `pierre.chevalier`
- lancer une recherche sur `myrna`
- cliquer sur le lien dans les résultats
- voir le carnet de myrna henderson
Se rendre sur la [review app](https://cdb-app-review-pr1377.osc-fr1.scalingo.io).
fix #1376

fix: carnet url

---

app/src/lib/ui/BeneficiaryList/Container.svelte
app/src/routes/(auth)/structures/[uuid]/+page.svelte
e2e/features/structureAdmin/beneficiary_list.feature
e2e/features/structureAdmin/dashboard.feature
e2e/features/structureAdmin/rattachementBeneficiaires.feature
e2e/features/structureAdmin/viewNotebook.feature
e2e/step_definitions/steps.js

ETQ admin de structure lorsque je choisi `Tous` dans la liste des bénéficiaires je vois trop de bénéficiaires, je vois des bénéficiaires qui ne sont pas dans ma structure.
Réparer le filtre pour n'afficher que les bénéficiaires de la structure
Se connecter en tant `lara.pafromage`
Aller sur la structure `Interlogement 93`
cliquer sur `Bénéficiaires non accompagnés`
Selectionner le filtre `Tous`
Valider qu'on affiche seulement 6 lignes
fix: #1380
Se rendre sur la [review app](https://cdb-app-review-pr1381.osc-fr1.scalingo.io).

fix: afficher seulement les bénéficiaires de la structure avec l'option tous

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/ui/BeneficiaryList/ProSearchResults.svelte
app/src/routes/(auth)/pro/+page.svelte
app/src/routes/(auth)/pro/_query.gql
e2e/features/admin_cdb/add_manager.feature
e2e/features/manager/importBeneficiaires.feature
e2e/features/manager/showListBeneficiairies.feature
e2e/features/manager/showListProfessionals.feature
e2e/features/manager/validateAccount.feature
e2e/features/orientationManager/filterBeneficiary.feature
e2e/features/pro/accueil/accueil.feature
e2e/features/pro/carnet/members.feature
e2e/features/pro/login.feature
e2e/features/structureAdmin/beneficiary_list.feature
e2e/step_definitions/steps.js

ETQ Pro j'ai besoin d'accéder à la liste des bénéficiaires de mon portefeuille depuis la page d'accueil
Afficher la liste des bénéficiaires du pro en bas de sa page d'accueil.
Se connecter avec `sanka` et vérifier, en bas de sa page d'accueil, la présence d'un tableau « Mes bénéficiaires » avec 3 bénéficiaires.
Se rendre sur la [review app](https://cdb-app-review-pr1401.osc-fr1.scalingo.io).
fix #1385

feat: ajout de la liste de bénéficaires sur la page d'accueil pro

---

backend/api/_gen/schema_gql.py
backend/scripts/codegen.sh

Le script qui génère le schéma GQL pour l'usage dans le backend ne respecte pas le format du linter `black`.
Ainsi, à chaque génération du fichier, le script de pre-commit modifie le fichier et il faut l'ajouter par la suite au commit.
On modifie le template contenu dans `backend/scripts/codegen.sh` pour que les `'''` soient correctement indentées.
RAS
Lancer le script `backend/scripts/odegen.sh`.
Lancer le script de pre-commit avec `pre-commit run all`.
Constater que toutes les vérifications sont des succès.
Se rendre sur la [review app](https://cdb-app-review-pr1409.osc-fr1.scalingo.io).

chore: Correction de l'indentation dans le schéma GQL généré (backend).

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
backend/api/_gen/schema_gql.py
backend/api/db/models/notebook_member.py
hasura/metadata/databases/carnet_de_bord/tables/public_structure.yaml
hasura/migrations/carnet_de_bord/1672908864766_alter_table_public_notebook_member_alter_column_active/down.sql
hasura/migrations/carnet_de_bord/1672908864766_alter_table_public_notebook_member_alter_column_active/up.sql

Lors que l'import de bénéficiaire, il est possible d'assigner directement un référent depuis son email si celui-ci existe déjà.
Malheureusement cela le fonctionne pas. Les notebook member sont bien créés mais le champ active est laissé à NULL ce qui ne permet pas de les voir.  
On supprime le fait que active puisse etre nullable  car il a une valeur par defaut à true. 
Un migration des données de prod est appliqué avant de supprimer la propriété nullable 
Se connecter en tant que manager.cd93 et réaliser un import en assignant un pro (pierre.chevalier).
voir la liste des bénéficiaires et valider que le pro est bien référent.
Se rendre sur la [review app](https://cdb-app-review-pr1412.osc-fr1.scalingo.io).
fix #1411

fix: suppression de la propriété nullable du champ active

---

DEMO.md
app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/ui/BeneficiaryList/_getStructuresWithPro.gql
app/src/lib/ui/OrientationManager/OrientationForm.svelte
e2e/features/manager/home.feature
e2e/features/manager/rattachement.feature
e2e/features/orientationManager/changeBeneficiaryOrientation.feature
e2e/features/orientationManager/filterBeneficiary.feature
e2e/features/orientationManager/manageOrientationRequest.feature
e2e/features/orientationManager/rattachement.feature
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_member.yaml

Actuellement les CO n'ont pas la possibilité de visualiser le nombre de place disponible pour la prise en charge des structures et des référents pour faire l'orientation/réorientation. 
N'ayant pas encore l'information de la jauge d'une structure, 
on affiche le nombre de carnets dans lequel le pro est référent (ex: Pierre Chevalier (3) 
et pour chaque structure le nombre de carnet dans lequel un pro de la structure est référent (ex: Groupe NS (1))
Etant donné qu'on utilise aussi ce formulaire pour les manager et pour les admin de structure, l'information remontera aussi pour ces derniers.
Se connecter en tant que `samy.rouate`
Aller sur la liste des bénéficiaires et faire une orientation 
Sélectionner le type d'orientation "Professionnel"
Sélectionner la structure Interlogement …

feat: afficher le nombre de carnet suivi par pro

---

app/src/hooks.server.ts

L'application front (Svelte) envoie toutes les erreurs de navigation vers Sentry.
Cela résulte en beaucoup de bruits concernant des routes non trouvées (eg. /wp-index.php) pour lesquelles aucune analyse ni action n'est nécessaire, au détriment des vrais erreurs qu'on souhaite traitées.
Avant d'envoyer l'erreur vers Sentry, on vérifie qu'il ne s'agit pas d'une 404 (`Not found`).
RAS
Sur la review app, accéder à une page inexistante.
Vérifier qu'aucune erreur Sentry n'est levée sur l'environnement `review`.
Ne pas supprimer ce bloc, qui sera mis à jour [automatiquement](.github/workflows/review-scalingo.yml).

chore: Amélioration des remontées d'erreur vers Sentry.

---

DEMO.md
app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/routes/index.ts
app/src/lib/ui/Deployment/View.svelte
app/src/lib/ui/StructureEdit/StructureCreationForm.svelte
app/src/lib/ui/StructureEdit/StructureEditLayer.svelte
app/src/routes/(auth)/admin/deployment/[uuid]/structures/+page.svelte
app/src/routes/(auth)/admin/deployment/[uuid]/structures/[structure_id]/+page.svelte
app/src/routes/(auth)/admin/deployment/[uuid]/structures/[structure_id]/+page.ts
app/src/routes/(auth)/admin/deployment/_getStructuresForDeployment.gql
app/src/routes/(auth)/manager/structures/+page.svelte
app/src/routes/(auth)/manager/structures/[structure_id]/+page.svelte
app/src/routes/(auth)/manager/structures/[structure_id]/+page.ts
app/src/routes/(auth)/manager/structures/[structure_id]/_getStructureById.gql
e2e/features/admin_cdb/add_manager.feature
e2e/features/admin_cdb/updateStructure.feature
e2e/features/manager/home.feature
e2e/features/manager/importBeneficiaires.feature
e2e/features/manager/importOrientationManager.feature
e2e/features/manager/importStructures.feature
e2e/features/manager/onboardingManager.feature
e2e/features/manager/rattachement.feature
e2e/features/manager/showListBeneficiairies.feature
e2e/features/manager/updateStructure.feature
e2e/features/manager/validateAccount.feature
e2e/features/manager/viewNotebook.feature
e2e/step_definitions/fr.js

closes #1393
Lorsqu'un administrateur de territoire ou un administrateur carnet de bord souhaite éditer les informations d'une structure, il doit le faire dans un formulaire assez riche qui s'affiche dans un volet.
Le formulaire est peu pratique à utiliser dans le volet.
Afficher le formulaire dans une page dédiée.
La page est disponible à l'adresse `/manager/structures/[structure_id]`.
On en profite pour renommer toutes les mentions "Admin PDI" en "Administrateur de territoire".
Se rendre sur la [review app](https://cdb-app-review-pr1418.osc-fr1.scalingo.io).
Se connecter en tant que `manager.cd93`.
Cliquer sur "Structures".
Cliquer sur l'icône "crayon" dans la colonne "Editer" en face d'une structure à modifier.
Vérifier que l'on est redirigé sur une page affichant le formulaire …

feat: Remplacement du volet du formulaire "Editer une structure" par une page.

---

app/src/routes/(auth)/pro/carnet/[uuid]/+page.svelte
e2e/features/pro/carnet/focuses.feature

Lorsque je me connecte en tant que pro (pierre.chevalier) et que je vais sur un carnet sur lequel je suis rattaché. 
Lorsque je crée le premier axe de travail, celui ci ne s'affiche pas (l'affichage n'est pas rechargé).
Cela est du à la manière dont fonctionne urql (la librairie utilisée pour les requete gql) 
ref: https://formidable.com/open-source/urql/docs/basics/document-caching/#document-cache-gotchas
On rajoute `notebook_focus`  dans la liste des `additionnalTypenames`
- Je me connecte en tant que pierre.chevalier
- Je recherche le carnet de kline
- Je clique sur "Se rattacher"
- Je clique sur "Rajouter un axe de travail"
- Je choisis"Numérique"
- Je valide
-  Je vois le nouvel axe de travail
Se rendre sur la [review app](https://cdb-app-review-pr1431.osc-fr1.scalingo.io).
fix #1430

fix: mise à jour de la liste des axes de travail

---

app/__tests__/triggers/notebookEvent.test.ts
app/package-lock.json
app/setupTest.ts
app/src/lib/ui/ProNotebookMember/ProNotebookMembersView.svelte
app/src/lib/ui/ProNotebookMember/ProNotebookMembersView.test.ts
app/src/routes/actions/matomo_dashboard/+server.ts
app/src/routes/actions/matomo_dashboard/_matomo_dashboard.test.ts
app/tsconfig.json
app/tsconfig.test.json
e2e/features/pro/carnet/members.feature

Actuellement lorsqu'un référent se détache de lui même du groupe de suivi, alors la personne n'est plus suivi et l'information ne parvient pas au Chargé d'orientation ce qui génère une rupture de parcours et bloque la réorientation
Pour éviter cela le détachement d'un pro "référent" doit se faire par une demande de réorientation. Il faut donc cacher le bouton se détacher pour les référents
Mise en place d'un test unitaire pour le composant NotebookMembersView.
On profite de l'ajout du test pour supprimer quelque message de log dans la sortie standart.
- Se connecter en tant que `pierre.chevalier` sur le carnet de sophie tifour et valider qu'on ne voit pas le bouton `Se détacher`
- Se connecter en tant que `sanka` sur le carnet de sophie tifour et valider qu'on voit bien le bouton `Se …

feat: un référent ne peut pas se détacher du groupe de suivi

---

app/src/lib/ui/AdminStructure/ImportProfessionals.svelte
app/src/lib/utils/sentry.ts
app/src/routes/(public)/inscription/request/+server.ts

Lorsqu'un administrateur de structure essaie d'importer un utilisateur déjà existant (avec le bouton `Importer une liste de professionnels` via un fichier csv) il n'a pas d'erreur explicite.
Le message d'erreur affiché est très générique et ne permet pas de comprendre que le compte existé déjà.
En analysant le bogue, on se rend compte que l'erreur lancée est une 500.
Dès lors, la question se pose sur la raison pour laquelle aucune erreur Sentry n'est reçue pour ce cas précis.
De plus, l'erreur qui est sensée être lancée est une 400 avec un log explicite.
cf. fichier [inscription/routes/+server.ts](https://github.com/gip-inclusion/carnet-de-bord/blob/dd7769dc27ee179d0940835112fc4b82cdcf6522/app/src/routes/(public)/inscription/request/%2Bserver.ts#L91).
La raison pour laquelle on ne reçoit …

fix: Afficher correctement l'erreur lors de la création d'un compte.

---

app/src/lib/ui/ProNotebookAction/ProNotebookActionList.svelte
e2e/features/pro/carnet/focuses.feature
hasura/metadata/databases/carnet_de_bord/tables/public_account.yaml
hasura/seeds/carnet_de_bord/seed-data.sql

Actuellement, lorsqu'un carnet contient une action (ou un objectif) crée par un pro dont le compte à été supprimé (ie: avec le champ `deleted_at` renseigné) la récupération de l'action fonctionne mais ne renvoie pas le créateur, ce qui crée une erreur dans le code. Cela est dû au fait que les pros n'ont pas les permissions suffisantes pour voir les `account` supprimés. Hasura met la proriété à null là où on attend un objet.
On permet de voir les `account` supprimés pour les pro dans les permissions.  
On met aussi à jour le code pour éviter de générer une erreur si l'on a pas de créateur
Se connecter en tant que pierre.chevalier sur le carnet de "Tifour"
Afficher l'axe de travail "logement"
Afficher l'objectif "Changer de logement"
Voir "Intervention face à une procédure d'expulsion"
Se …

fix: suppression de l'erreur lors de la consultation d'un axe

---

.pre-commit-config.yaml

Depuis quelques jours, une mise à jour de `poetry-core` entraîne un échec d'installation de l'outil `isort` utilisé par notre configuration de `pre-commit` : https://github.com/PyCQA/isort/issues/2077
Une mise à jour de `isort` a été publiée (5.12.0) qui corrige le problème. Dans cette PR, on met à jour notre configuration `pre-commit` pour utiliser cette version.
Confirmer que le workflow `Test` passe bien sur cette PR.

ci: mise à jour de isort pour corriger l'échec pre-commit

---

app/src/routes/auth/login/+page.svelte

Suite à l'ajout de l'action du  bouton "Renvoyer le mail de connexion", on observe un nombre croissant de demande de courriel de connexion dans une labs de temps très court. Cela impacte de plus la délivrabilité des mails en surchargeant anormalement le nombre d'envoi d'email. On observe aussi un nombre croissant de mail dont l'état est "différé" dans tipimail. Cela est du au fait que nous sommes en plus limité dans l'envoi de mail de connexion ayant un nouveau compte sur tipimail.
On désactive la possibilité de renvoyer le mail en attendant de trouver une solution plus perenne.
ras
- aller sur la page de connexion
- saisir "pierre.chevalier"
- ouvrir les devtools
- cliquer sur renvoyer le lien
- valider qu'aucun appel réseau ne soit fait.
Se rendre sur la [review …

fix: suppression de l'action de renvoi de mail de connexion

---

backend/bin/post_compile
backend/cron.json

La fréquence des emails de rappel est trop élevée, et l'heure d'envoi ne convient pas nécessairement.
Permettre de définir la programmation des envois via une variable d'environnement.
La variable d'environnement utilisée est `REMINDER_EMAIL_SCHEDULE`. Si elle n'est pas définie on utilise une programmation par défaut. Si cette variable est modifiée il faudra bien penser à redéployer l'application pour que le changement soit pris en compte.
Se rendre sur la [review app](https://cdb-app-review-pr1485.osc-fr1.scalingo.io).

feat: permettre la configuration des rappels par une variable

---

app/src/lib/ui/ProNotebookMember/ProNotebookMembersView.svelte
app/src/lib/ui/ProNotebookMember/ProNotebookMembersView.test.ts

Actuellement, sur la page d'un carnet, les chargés d'orientation voient un bouton se « détacher » qui ne fonctionne pas car tout le code de cette page a été prévu pour uniquement détacher les professionnels.
Désactivation du bouton « se détacher » pour chargé d'orientation. Une nouvelle méthode sera mise en place dans une autre PR pour que les CO puissent se détacher directement à partir de la liste des bénéficiaires.
RAS
1. Je me connecte en tant que `samy.rouate`
2. Je vais sur le carnet de `Terry Horn`
3. Je confirme qu'il n'y a plus de bouton « Se détacher » dans la partie « Groupe de suivi »
Se rendre sur la [review app](https://cdb-app-review-pr1486.osc-fr1.scalingo.io).
fix #1484

fix: affichage du bouton se détacher uniquement pour les pros

---

e2e/features/pro/carnet/reorientation.feature
hasura/metadata/databases/carnet_de_bord/tables/public_orientation_request.yaml
hasura/migrations/carnet_de_bord/1675255129484_alter_table_public_orientation_request_alter_column_status/down.sql
hasura/migrations/carnet_de_bord/1675255129484_alter_table_public_orientation_request_alter_column_status/up.sql

Aujourd'hui quand une demande de réorientation est cours, le professionnel peut toujours faire une demande réorientation via le bouton "demander une réorientation".
Le bouton est affiché car on vérifie que la demande n'est pas dans l'état `pending`. Cependant, la valeur par défaut lors de l'insertion (configuré par Hasura) est `current`.
On décide donc de supprimer cette configuration Hasura.
On la remplace par une valeur par défaut lors de l'insert SQL, qui vaut `pending`.
On ajoute une migration de données qui change tous les statuts `current` en `pending`.
RAS
Se rendre sur la [review app](https://cdb-app-review-pr1487.osc-fr1.scalingo.io).
Se connecter en tant que `pierre.chevalier`.
Se rendre sur le carnet de Sophie Tifour.
Faire une demande de réorientation.
Vérifier que le bouton …

fix: Ne pas afficher le bouton "Demander une réorientation" si une demande et déjà en cours.

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/ui/ProfessionalList/_getProfessionalsForStructure.gql
e2e/features/structureAdmin/edit_professional.feature

Je me connecte en tant que jacques.celaire.
J'affiche la liste de pro de ma structure.
Je vois que pierre chevalier suit 2 personnes alors qu'il n'est référent que d'un seul bénéficiaire.
On ne filtre (referent + actif) pas l'aggregat des notebook_member dans la requete GetProfessionalsForStructure.
On ajoute le même filtre pour le compte que pour l'affichage de la liste des bénéficiaires.
RAS
Se rendre sur la [review app](https://cdb-app-review-pr1496.osc-fr1.scalingo.io).
Je me connecte en tant que jacques.celaire.
J'affiche la liste de pro de ma structure.
Je vois que pierre chevalier suit 1 personne.
fixes #1493

fix: La pastille du nombre de bénéficiaires suivis est fausse

---

app/src/lib/ui/OrientationHeader/OrientationHeader.svelte
app/src/lib/ui/OrientationHeader/OrientationHeader.test.ts

Les administrateurs de structure ne font pas de réorientation, aussi l'API permettant cette réorientation leur interdit l'opération.
Cependant, le bouton `Orienter`/`Réorienter` est toujours affiché pour les administrateurs de structure.
On n'affiche plus le bouton `Orienter`/`Réorienter` pour les administrateurs de structure.
On en profite pour ajouter des tests au niveau composant sur cet affichage, plutôt que des tests end-to-end.
Se rendre sur la [review app](https://cdb-app-review-pr1495.osc-fr1.scalingo.io).
Je me connecte en tant que jacques.celaire
J'affiche le liste des bénéficiaires de la structure
J'affiche le carnet de Aguilar
Je ne vois pas le bouton "Réorienter" car les admin de structure ne font pas de réorientation
fixes #1492

fix: Ne pas afficher le bouton "Orienter"/"Réorienter" pour les administrateurs de structure.

---

app/elm/Diagnostic/Main.elm
app/elm/Diagnostic/Main.elm.d.ts
app/elm/Domain/SituationPro.elm
app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/ui/Beneficiary/SocioProView.svelte
app/src/lib/ui/ProNotebookSocioPro/ProNotebookSocioPro.schema.ts
app/src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProUpdate.svelte
app/src/lib/ui/ProNotebookSocioPro/_UpdateSocioPro.gql
app/src/routes/(auth)/beneficiaire/_getNotebookByBeneficiaryId.gql
app/src/routes/(auth)/pro/carnet/_getNotebook.gql
backend/cdb/api/_gen/schema_gql.py
e2e/features/pro/carnet/sociopro.feature
hasura/metadata/databases/carnet_de_bord/tables/public_notebook.yaml
hasura/migrations/carnet_de_bord/1675941150892_alter_table_public_notebook_add_column_last_job_date/down.sql
hasura/migrations/carnet_de_bord/1675941150892_alter_table_public_notebook_add_column_last_job_date/up.sql

Actuellement nous n'avons pas la date du dernier emploi dans carnet de bord. On souhaiterait la rajouter comme information dans le bloc du diagnostic socio-professionnel.
On rajoute le champs dans le bloc de diagnostic et dans le formulaire de mise à jour des infos sociopro
la date du dernier emploi est enregistrée dans le champs `last_job_ended_at` dans la table `notebook`
- Se connecter en tant que pierre.chevalier
- Aller sur le carnet de `sophie.tifour`
- Éditer les infos socio professionnelles
- saisir une date dans le champs date de fin du dernier emploi
- Valider
- S'assurer que la date s'affiche bien dans le bloc `Diagnostic socioprofessionnel` 
Se rendre sur la [review app](https://cdb-app-review-pr1513.osc-fr1.scalingo.io).
fix #1512

feat: ajout de la date du dernier emploi

---

DEVELOPING.md
docker-compose-test.yaml
docker-compose.yaml
scripts/launch_tests.sh

Actuellement nous ne n'utilisons la propriété `name` dans nos fichiers docker compose. cela empêche de pouvoir arrêter / relancer les environnements de développement ou de test indépendamment via la commande  `docker compose`
On ajoute la propriété name dans le docker compose de test
On profite de la pr pour permettre de lancer le script `launch_test.sh` d'autres part que la racine du projet.
On supprime aussi les `restart: always` qui relance les container au demarrage de la machine si ces derniers était lancés.
On ajoute `stop_signal: SIGKILL` pour stopper les container hasura vu que l'app est immutable
On profite d'aligner les versions de pg avec celle de prod 
- lancer le script launch_test.sh
- lancer la commande  `docker compose --project-name cdb-test down`
- vérifier que les …

chore: add name in docker project

---

app/elm/Diagnostic/Main.elm
app/elm/Diagnostic/Main.elm.d.ts
app/elm/Domain/Account.elm
app/elm/Domain/Structure.elm
app/elm/Domain/Theme.elm
app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/ui/Beneficiary/SocioProView.svelte
app/src/lib/ui/OrientationManager/NotebookEdit.svelte
app/src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProView.svelte
app/src/lib/ui/views/NotebookView.svelte
app/src/routes/(auth)/beneficiaire/_getNotebookByBeneficiaryId.gql
app/src/routes/(auth)/pro/carnet/[uuid]/+page.svelte
app/src/routes/(auth)/pro/carnet/_getNotebook.gql
app/src/routes/+page.svelte
e2e/features/orientationManager/carnet/focus.feature
e2e/features/pro/carnet/focuses.feature

En tant que chargé d'orientation / professionnel, j'ai besoin de consulter et mettre à jour le diagnostic socioprofessionnel afin d'appréhender la réalité de la situation du bénéficiaire et d'adapter mon accompagnement.
Concerne l'issue #1461 
Ajouter dans "Diagnostic socioprofessionnel" un bloc "Situation personnelle" qui permettra d'afficher « à plat » les informations de la situation personnelle.
RAS
Se rendre sur la [review app](https://cdb-app-review-pr1517.osc-fr1.scalingo.io).
Se connecter en tant que `pierre.chevalier`, aller sur le carnet de `Sophie Tifour`, constater l'affichage de ses informations personnelles.
fix #1461

feat: ajout de la situation personnelle

---

backend/cdb/api/v1/routers/notebooks.py
backend/tests/api/test_notebooks.py

Lorsqu'un pro se rattache à un carnet sans avoir de mandat, on affecte le bénéficiaire à la structure du pro alors que cela ne devrait  être fait que dans le cas ou le pro à un mandat (comme référent) 
Modifer le rattachement à une structure seulement lorsqu'un pro se rattache à un carnet et qu'il à un mandat
ras
se connecter en tant que `pierre.chevalier`
se rattaché à Buckley Hoffman en tant que pro sans mandat (donc non référent).
Sel connecter en tant `manager.cd93`
Verifier que Buckley Hoffman n'est toujours pas suivi par une structure
fix #1551
Se rendre sur la [review app](https://cdb-app-review-pr1552.osc-fr1.scalingo.io).

fix: ne pas modifier la structure de suivi en cas de rattachement en tant que no-referent

---

app/package-lock.json

This reverts commit f153529dd8350842dce2d3e8defdb8d639316ae6.
la mise à jour d'undici entraine une impossibilité de se connecter en dev `npm run dev`
on revert la mise à jour d'undici en attendant de pouvoir mieux comprendre d'ou vient le problème
ras
Lancer l'environnement de dev en local et se connecter à l'appli avec un compte de démo
Se rendre sur la [review app](https://cdb-app-review-pr1567.osc-fr1.scalingo.io).

Revert "build(deps): bump undici from 5.11.0 to 5.20.0 in /app (#1542)"

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/ui/BeneficiaryList/SupportFilters.svelte
app/src/lib/ui/BeneficiaryList/supportFilter.schema.ts
app/src/routes/(auth)/manager/+page.svelte
app/src/routes/(auth)/manager/_getDeploymentInfo.gql
app/src/routes/(auth)/manager/beneficiaires/+page.svelte
app/src/routes/(auth)/manager/beneficiaires/+page.ts
e2e/features/manager/home.feature

la home affiche un nombre de bénéficiaires qu'on ne retrouve pas lorsqu'on affiche la liste des bénéficiaires. Le dénombrement de l'accueil etait faux (nombre de bénéficiaire sans structure ou sans membre actif dans le groupe de suivi et le filtre de la liste bénéficiaire qui filtrer les bénéficiaires avec ou sans référent.
On met à jour les filtres avec  accompagnés, non accompagnés, et en attente de référent à la liste des bénéficiaires
On en profite pour mettre à jour le dashboard manager (et ses test e2e)
Se connecter en tant que `manager.cd93`
Suivre les liens   `bénéficiaires non accompagnés` depuis l'accueil du dashboard
Constater qu'on a bien 2 bénéficiaires
Se rendre sur la [review app](https://cdb-app-review-pr1537.osc-fr1.scalingo.io).
fix #1489

fix(manager): mise à jour de la liste bénéficiaires et du dashboard

---

DEVELOPING.md
app/src/lib/emailing/send.ts
backend/cdb/api/core/sendmail.py

Maildev a été retiré avec db957f984a919b6539672fd33af6a4e242eed071, les environnements hors prod utilisent tous mailtrap
🗑
Se rendre sur la [review app](https://cdb-app-review-pr1568.osc-fr1.scalingo.io).

chore: retirer les références à maildev

---

app/elm/Diagnostic/Main.elm

Actuellement, lorsque aucune situation personnelle n'est renseignée, le système affiche un tableau vide mais ne permet pas de comprendre de manière explicite qu'il n'y a pas encore de situation identifiée.
Utiliser la review app :
- en tant que pierre.chevalier
- aller dans le [CdB de Sophie Tifour](http://localhost:3000/pro/carnet/9b07a45e-2c7c-4f92-ae6b-bc2f5a3c9a7d)
- mettre à jour la situation personnelle en décochant tous les éléments
- Enregistrer
Ne pas supprimer ce bloc, qui sera mis à jour [automatiquement](.github/workflows/review-scalingo.yml).
Closes #1534

feat: afficher un placeholder quand la situation personnelle est vide

---

INSTALL.md
TESTING.md
backend/README.md
e2e/README.md

Communiquer les différentes suites de tests de l’application aux développeurs.
S’assurer que l’installation de l’environnement permette immédiatement de lancer les tests.
Documenter `npm run test:{elm,svelte}`.
Offrir un aperçu des tests disponible depuis la racine du projet.
Se rendre sur la [review app](https://cdb-app-review-pr1573.osc-fr1.scalingo.io).

chore: ajouter de la documentation pour les tests

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/ui/ProNotebookSocioPro/_UpdateSocioPro.gql
app/src/routes/(auth)/beneficiaire/_getNotebookByBeneficiaryId.gql
app/src/routes/(auth)/pro/carnet/_getNotebook.gql
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_situation.yaml
hasura/migrations/carnet_de_bord/1677550512224_add-deleted-columns-on-notebook-situation/down.sql
hasura/migrations/carnet_de_bord/1677550512224_add-deleted-columns-on-notebook-situation/up.sql

En tant que professionnel, j'ai besoin de conserver l'évolution de la situation personnelle du bénéficiaire afin d'adapter son accompagnement.
Historiser la suppression des situations personnelles lors de la mise à jour du diagnostic
Pour cela, on ajoute les colonnes `deleted_at` et `deleted_by` à la table `notebook_situation`.
RAS
Se rendre sur la [review app](https://cdb-app-review-pr1570.osc-fr1.scalingo.io).
Se connecter en tant que `pierre.chevalier`.
Se rendre sur le carnet de Sophie Tifour.
Supprimer une situation existante.
Rétablir la situation précédemment supprimée.
Vérifier que la situation est bien ajoutée et que la date de création correspond à la date du jour.
closes #1523

feat: Historiser les changements de situations d'un bénéficiaire

---

.github/pull_request_template.md
.github/workflows/review.yml

L’action blablacar est dépréciée (runs on Node 12).
Utiliser une autre action, le but est simplement d’avoir un lien vers la recette.
Le lien vers la recette est maintenant fourni par un commentaire.

chore: notifier la création de la review app par un commentaire

---

app/src/routes/+page.svelte
app/tailwind.config.cjs

Maintenir une liste des classes Tailwind utilisées par Elm dans Svelte est fastidieux, avec un fort risque d’erreur.
Ajouter les fichiers elm dans la liste des fichiers à surveiller par Tailwindcss.
Naviguer sur la recette, les styles doivent être en place.
Se rendre sur la [review app](https://cdb-app-review-pr1581.osc-fr1.scalingo.io).

chore: pass Elm styles to tailwindcss

---

DEVELOPING.md

Améliore la visibilité des ADR, pour permettre aux nouveaux membres de
l’équipe de se documenter sur les choix importants de l’équipe.

chore: diriger les développeurs vers les ADR

---

app/src/routes/(auth)/manager/professionnels/+page.svelte
e2e/features/manager/validateAccount.feature

Actuellement lorsqu'un admin de structure supprime un pro, celui disparait bien de la structure mais reste affiché pour le manager. Il n'y a pas de moyen de distingué l'état du compte du pro (non confirmé, confirmé , supprimé) 
On rajoute l'information de suppression de compte sous forme d'un badge dans la liste des pro
se connecter avec `manager.cd93`
cliquer sur `professionnels`
Voir que sarah.vigote et bien supprimé.

feat: Afficher le statut de chaque compte (supprimé / confirmé / non-confirmé) pour l'administrateur de territoire.

---

app/src/lib/ui/Beneficiary/NotebookMembers.svelte

Le composant Radio installe déjà une `div.fr-form-group`.
Retirer la div en doublon.
Vérifier le comportement de la modale “Se rattacher” lorsqu’un pro décide de se rattacher à un bénéficiaire.

chore: retirer une div en doublon sur NotebookMembers

---

app/elm.json
app/elm/Diagnostic/Main.elm
app/elm/Diagnostic/Main.elm.d.ts
app/elm/Domain/ProfessionalProject.elm
app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/ui/Beneficiary/SocioProView.svelte
app/src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProUpdate.svelte
app/src/routes/(auth)/beneficiaire/_getNotebookByBeneficiaryId.gql
app/src/routes/(auth)/pro/carnet/_getNotebook.gql
hasura/metadata/databases/carnet_de_bord/tables/public_professional_project.yaml
hasura/migrations/carnet_de_bord/1678998383915_alter_table_public_professional_project_add_column_updated_by/down.sql
hasura/migrations/carnet_de_bord/1678998383915_alter_table_public_professional_project_add_column_updated_by/up.sql

Lorsqu'un professionnel consulte le projet d'un bénéficiaire, il ne connait pas la date et l'auteur de la dernière mise à jour du projet.
On enregistre l'auteur de chaque mise à jour de projet professionnel dans le champ `updatedBy`.
On affiche l'auteur, sa structure et la date de mise à jour de chaque projet professionnel.
Il faut modifier la mise à jour actuel car on met à jour tous les projets professionnels à chaque enregistrement ...
Se connecter en tant que `pierre.chevalier`.
Se rendre sur un carnet.
Vérifier que les dates de mises à jour des projets professionnels sont affichées.
Ouvrir le formulaire d'édition d'un diagnostic socioprofessionnel.
Enregistrer le diagnostic sans faire de modification.
Vérifier que les dates de mises à jour des projets professionnels n'ont pas changé. …

feat: Affichage des informations de mise à jour des projets professionnels.

---

.github/workflows/release.yml
.github/workflows/test.yml

Chaque commit sur `master` entraine la création d'une release.
Cela se traduit par un commit supplémentaire qui est lui-même taggé.
La création de ce commit automatique annule les tests qui sont en cours sur le commit précédent.
Cela entraine une CI en échec un commit sur deux, ce qui ne reflète pas l'état réel de la branche `master`.
Sur la branche `master`, on ne déclenche plus les tests sur les commits qui ne sont pas des release.
RAS
Les tests ne devront être exécutés qu'une seule fois lors du merge sur `master`.

chore: Tester la branche `master` uniquement pour les releases.

---

app/elm/Domain/ProfessionalProject.elm

Une erreur d'orthographe s'est glissée dans le type de contrat `saisonnier` (oubli d'un `n` dans la liste de choix).
Ajout du `n` manquant.
Merci Arnaud !
Se rendre sur un carnet en édition.
Vérifier que la liste de choix de type de contrat affiche `Saisonnier`.

fix: Correction de la faute dans le nom du type de contrat `saisonnier`.

---

hasura/migrations/carnet_de_bord/1680096458377_add-ref-theme/up.sql

Suite au déploiement en production de la v1.212.0, la migration `add-ref-theme` qui fusionne plusieurs `notebook_target` vers un seul élément a échoué.
En regardant la migration qui a échoué, on constate que c’est cette ligne qui a créé l’insertion de la donnée qui a échoué :
```bash
UPDATE "public"."notebook_target" SET target='Trouver sa formation' WHERE target IN('Se former', 'Acquérir les compétences de bases', 'Se remobiliser', 'Accéder au parcours d’accompagnement');
```
Dans cette ligne, on met à jour la target avec le texte “Trouver sa formation” pour tous les `notebook_target` dont la target actuelle est parmi “Se former”, “Acquérir les compétences de bases”, “Se remobiliser” et “Accéder au parcours d’accompagnement”.
En regardant les données dans metabase, on peut chercher les …

fix: Correction de la fusion de plusieurs `notebook_target` vers un seul élement.

---

app/elm/Domain/ProfessionalProject.elm

Lors de la saisie du type de contrat d'un projet professionnel, la sélection du type `Libéral` entraine une erreur, empêchant la sauvegarde du projet professionnel.
Cela est du à une typo dans l'enum utilisé (`liberale` côté `elm`, `liberal` côté `postgresql`).
Corriger la typo dans l'enum `elm`.
RAS
Se connecter en tant que `pierre.chevalier`.
Se rendre sur le carnet de `Sophie Tifour`.
Modifier les projets professionnels.
Sélectionner `Libéral` comme type de contrat.
Enregistrer les projets professionnels.
Vérifier que le projet est enregistré avec le type de contrat `Libéral`.
closes #1619

fix: Correction de l'impossibilité de choisir le type de contrat `libéral`.

---

hasura/metadata/databases/carnet_de_bord/tables/public_account.yaml
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_member.yaml

En tant qu’Administrateur de structure, quand je consulte un carnet, je ne vois pas le chargé d'orientation.
Les permissions des tables `account` et `notebook_member` sont trop restrictives : elles limitent la visibilité pour les Administrateurs de structure aux seuls professionnels du même déploiement.
On ajoute donc la visibilité des chargés d'orientation dont le déploiement est le même que celui de l'Administrateur de structure.
RAS
Se connecter en tant que `jacques.celaire`.
Se rendre sur le carnet de `Sophie Tifour`.
Vérifier que `Giulia Diaby` apparaît comme Chargé d'orientation.
closes #1633

fix: Permettre aux administrateurs de structure de voir les membres de carnet au sein du même déploiement.

---

app/package-lock.json
app/package.json

En faisant un `npm audit`, on peut voir que SvelteKit présente la vulnérabilité suivante :
> SvelteKit vulnerable to Cross-Site Request Forgery - https://github.com/advisories/GHSA-5p75-vc5g-8rv2
> SvelteKit framework has Insufficient CSRF protection for CORS requests - https://github.com/advisories/GHSA-gv7g-x59x-wf8f
Mettre à jour SvelteKit avec la version 1.15.4.
RAS
Vérifier que les tests automatisés passent.
Aucun changement fonctionnel n'est apporté.

chore: Mise à jour de SvelteKit pour supprimer la vulnérabilité CSRF.

---

DEVELOPING.md
INSTALL.md
Makefile
TESTING.md

La procédure d'installation et de démarrage est claire et bien documentée. Mais elle pourrait être plus simple.
`make install` est une commande classique. Dans notre cas elle permet d'automatiser les différentes commandes nécessaire à l'installation du projet.
Make est un outil bien supporté. Les shells proposent de l'auto-complétion pour les commandes make. Cela facilite le démarrage de l'application grâce à deux targets: start-front et start-back
Aller dans le répertoire racine du projet et lancer les commandes suivantes : 
```bash
make install
make start-app
make start-backend
```

chore: ajout d'un Makefile

---

.github/workflows/deploy.yml

En essayant de ne pas annuler les déploiements de release en cours, on bloque les déploiements en preprod car le workflow de déploiement attend la validation des environnements pour être considéré comme terminé.
On revert le changement précédent en attendant une meilleure solution au problème initial.
RAS
RAS

Revert "chore: Ne pas annuler le déploiement d'une release en cours."

---

app/elm.json

fixes elm-test on the ci
Elm test ne fonctionne pas apparemment à cause d'un problème de version de dépendances
Mise à jour avec elm-json des dépendances (y compris les dépendances majeures)
Faire un tour sur le site pour confirmer la compilation des différentes pages. Et la CI github devrait valider la modification.

chore: upgrade elm dependencies

---

scripts/create-review-apps.sh

Lors de la création de la tâche périodique via Hasura, une coquille s'est glissée dans la création de la variable d'environnement `BACKEND_API_URL`pour la review app d'Hasura.
Corriger la coquille (remplacer `app` par `hasura`).
RAS
Les reviews app doivent se déployer sans problème.

chore: Ajouter la variable BACKEND_API_URL dans les déploiements des review app Hasura.

---

backend/cdb/api/db/models/nir.py
backend/tests/test_nir_check.py

L'import d'un NIR avec une lettre (Corse) échoue.
Autoriser le A et le B dans le NIR pour les codes postaux de la Corse.
Importer des bénéficiaires avec un NIR corse et vérifier que le NIR est accepté
fix #1671

fix: allow NIR from corse

---

app/svelte.config.js

En regardant la console de l'environnement de démo, on constate qu'il existe encore deux ⚠️ warnings ⚠️ liés aux CSP :
```
The source list for the Content Security Policy directive 'connect-src' contains an invalid source: ***redacted Sentry URL***. It will be ignored.
```
et
```
Refused to load the script 'https://matomo.inclusion.beta.gouv.fr/matomo.js' because it violates the following Content Security Policy directive: "script-src 'self'  ***redacted Crisp URL***". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```
On risque d'avoir des problèmes de non remontée d'information (tracking + monitoring des erreurs) lors de la prochaine mise en production.
Concernant le warning lié à l'URL Sentry, celui-ci est du au fait que la variable …

fix: Corrige les CSP.

---

app/__tests__/csp.test.ts
app/src/hooks.server.ts
app/src/lib/utils/csp.ts
app/svelte.config.js

La _Content Security Policy_ (CSP) générée par SvelteKit actuellement ne prend pas en compte les changements de variables d'environnements après le déploiement (build) de l'application. Ceci pose un problème pour les _review apps_ qui sont reconfigurées après leur déploiement.
De plus, il manque une directive `connect-src` pour permettre l'envoi de données à Matomo.
SvelteKit ne permet pas d'évaluer dynamiquement la CSP. Pour contourner cette limitation, on utilise des marqueurs de la forme `%GRAPHQL_API_URL%` dans les directives fournies à SvelteKit, qui sont ensuite remplacés à la volée dans un _hook_ qui traite les réponses HTTP avant l'envoi au client.
Vérifier le bon fonctionnement en _review app_, y compris la remontée vers Matomo et Sentry.

Gestion des variables d'environnement dynamiques dans la Content-Security-Policy

---

backend/cdb/caf_msa/parse_infos_foyer_rsa.py
backend/tests/caf_msa/test_parse_infos_foyer.py

Certains utilisateurs / utilisatrices ne reçoivent pas le courriel récapitulatif lors d'un import de fichier CAF/MSA.
En regardant les logs, on voit que le traitement en tâche de fond échoue :
```
2023-05-03 15:41:33.201268961 +0200 CEST [web-1] {"logger": "cdb.caf_msa.update_cafmsa_infos", "level": "error", "timestamp": "2023-05-03T13:41:33.134648Z", "sentry_id": "0c00a5cbd8be483d926514fe0874dfe4", "message": "1 validation error for CafBeneficiary\nsoumis_droit_et_devoir\n  none is not an allowed value (type=type_error.none.not_allowed)"}
```
Après analyse, il apparait que l'information `soumis au droit et devoir` n'est pas une information obligatoire.
La donnée `soumis au droit et devoir` est bien une donnée optionnelle en base de données.
En revanche, lors du parsing du fichier, le …

fix: Rend optionnelle la donnée soumis aux droits et devoirs lors de l'import.

---

flake.lock
flake.nix

Le setup nix actuel pose des problèmes avec le lancement des tests ou du serveur. Il semble y avoir des conflits de contexte entre nix et poetry.
Supprimer les dépendances python explicites et utiliser poetry uniquement.
Pour que ce setup fonctionne, j'ai ajouté libxml2 et ses dépendances dans le setup.
Lancer les tests end to end dans le contexte nix. S'ils fonctionnent correctement c'est que le setup est juste.
```bash
nix develop
make install
./scripts/launch_tests.sh e2e
```

chore: Suppression de dépendances superflues de flake.nix

---

.github/workflows/deploy.yml

L'action GitHub qui notifie d'un nouveau déploiement en production affiche les warnings suivants :
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: SamhammerAG/last-successful-build-action@a54c030db88e60c06a9e50c25418748afc623c20. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Le premier warning concerne l'utilisation de Node.js 12 par l'action `SamhammerAG/last-successful-build-action`.
La dernière …

chore: Suppression du warning lors de la notification d'un nouveau déploiement.

---

app/elm/README.md
app/src/lib/ui/Beneficiary/SocioProView.svelte
app/src/lib/ui/NPSRating/NPSRating.svelte
app/src/lib/ui/ProNotebookAction/ProNotebookActionList.svelte
app/src/lib/ui/ProNotebookPersonalInfo/ProNotebookPersonalInfoView.svelte
app/src/lib/utils/ElmWrapper.svelte
app/src/routes/(auth)/pro/carnet/[uuid]/+page.svelte

Lors du développement de l'application front, on rencontre des erreurs lors du rechargement à chaud de certains composants elm (`elm-hot-reload`), bien que ces erreurs ne soient pas présentes en production, on préfère s'en prémunir dès le développement pour éviter de masquer d'autres erreurs.
On utilise le composant `ElmWrapper.svelte` partout où on utilise un composant elm.
On change le montage du composant elm dans `onMount` (au premier affichage de la page) plutôt qu'à l'événement `onUpdate` qui est appelé à chaque rafraichissement de la page.
Ces mises à jour de page arrivent fréquemment quand on développe car l'application "watch" les changements de fichiers et recharge la page courante. C'est dans ces conditions que le rechargement à chaud de elm et de svelte entrent en conflit (elm …

chore: Améliore le montage des éléments elm.

---

app/src/app.css
app/src/lib/ui/ProNotebookMember/ProAppointment.svelte

Lors de la refont du header, la couleur "france-bleu" a été supprimée.
Il reste néanmoins une utilisation dans l'entête du tableau des rendez-vous.
Voir ce message : https://github.com/gip-inclusion/carnet-de-bord/pull/1732#issuecomment-1545317427.
On supprime la classe en question et on laisse le design du DSFR.
RAS
Se rendre sur un carnet.
Vérifier que le tableau des rendez-vous a une entête grise (et non bleu).

feat: Suppression du bleu france.

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
backend/cdb/api/_gen/schema_gql.py
hasura/migrations/carnet_de_bord/1683801154520_alter_table_public_manager_add_unique_email_deployment_id/down.sql
hasura/migrations/carnet_de_bord/1683801154520_alter_table_public_manager_add_unique_email_deployment_id/up.sql

Actuellement on ne peut pas créer plusieurs compte d'administrateur avec le même courriel sur des territoire différent, ce qui est problématique pour certains déploiement ou la même personne opère sur 2 déploiements différent cf #1722
On ajoute l'id du deploiement à la contrainte d'unicité de l'email
ras
se connecter en tant qu'admin et créer  2 déploiements avec le même courriel d'admin

feat: ajoute le deploiement à la contrainte d'unicité sur l'email des  manager

---

.github/workflows/release.yml
.github/workflows/test.yml
app/src/lib/ui/base/Footer.svelte

La branche principale s'appelle `master` ce qui n'est pas très inclusif.
Suite au sondage entre dev, c'est le nom `main` qui est choisi.
On remplace les occurences de `master` en `main`.
Ne pas oublier de renommer la branche sur GitHub avant de merger.
Il faut également que chaque dev renomme localement en suivant ces étapes.
https://gist.github.com/danieldogeanu/739f88ea5312aaa23180e162e3ae89ab
Aucune idée.

chore: Renommage de la branche `master` en `main`.

---

.github/workflows/release.yml

Suite au renommage de la branche `master` en `main`, le worklfow de release est en échec.
Après analyse, il appraît que l'action `semantic-release` a une configuration des branches par défaut qui contient `master`, ce qui était pratique jusqu'alors mais ne fonctionne plus avec `main`.
On spécifie la branche `main` dans les options de `semantic-release`.
On en profite pour passer à la version 3 de `semantic-release` et ainsi supprimer le warning relatif à l'utilisation de `node 12`.
Merger et croiser les doigts pour que la release soit bien réalisée.

chore: Spécifier la branche à release.

---

app/src/routes/v1/[...endpoint]/+server.ts

Suite à la mise en prod de la PR #1698, l'envoi de fichier ne marchait plus mais seulement sur scalingo (les tests e2e lançaient en local ou depuis la CI fonctionnaient)
Après investigations, il s'est avéré que le problème était du à un header manquant (Accept-encoding) entrainant une erreur d'encodage sur scalingo.  Le soucis avait été rencontré lors de la mise en place de la route `/graphql` dans sveltekit. La solution avait été de rajouter le header `Accept-encoding: Identity`. Nous avons donc rajouté ce header qui a permis de résoudre le soucis
- se connecter en tant que manager.cd93
- importer un fichier de bénéficiaire
- voir le recap du fichier 
fix #1739

fix: Corrige l'import de fichiers de bénéficiaires.

---

app/src/lib/ui/ProBeneficiaryUpdate/ProBeneficiaryUpdateFields.svelte
app/src/lib/ui/ProNotebookPersonalInfo/ProNotebookPersonalInfoUpdate.svelte

La ville et le code postal sont décalés sur le formulaire de modification des informations personnelles. Les cases à cocher sont trop serrées.
On corrige le souci de margin sur la ville et le code postal et on applique le DSFR pour les cases à cocher.
On s'assure que le rendu ressemble bien à celui-là.
fix #1744

fix: problèmes d'affichage sur le formulaire de mise à jour des informations personnelles

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/tracking/matomo.ts
app/src/routes/actions/matomo_dashboard/_getDeploymentStats.gql
backend/cdb/api/_gen/schema_gql.py
backend/cdb/api/db/crud/notebook.py
backend/cdb/api/db/models/action.py
hasura/metadata/databases/carnet_de_bord/tables/public_notebook.yaml
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_action.yaml
hasura/migrations/carnet_de_bord/1684333811675_alter_table_beneficiary_index/down.sql
hasura/migrations/carnet_de_bord/1684333811675_alter_table_beneficiary_index/up.sql
hasura/migrations/carnet_de_bord/1684334642154_create_index_notebook_member_notebook_id/down.sql
hasura/migrations/carnet_de_bord/1684334642154_create_index_notebook_member_notebook_id/up.sql
hasura/migrations/carnet_de_bord/1684334846968_alter_table_public_notebook_action_drop_column_initial_id/down.sql
hasura/migrations/carnet_de_bord/1684334846968_alter_table_public_notebook_action_drop_column_initial_id/up.sql

Une erreur est levée toute les nuits à 1h00 CEST. Après investigation, l'erreur provient du cron qui lance le script matomo_dashboard. Ce script mets plus de 60s à s'éxécuter ce qui entraine un timeout de la part du router scalingo. Le script quant à lui poursuit son exécution sans erreur.  
La requête graphql initiale utilisée un champ calculé (nb_member) qui n'utilisait pas le champ `active` ce qui avait pour conséquence de ne pas profiter de l'index sur les champs notebook_id / active=true
Suite à une mise à jour d'Hasura, il est maintenant possible de se passé du champ calculé et d'exprimer la requête en graphql.
Au cours de l'investigation, plusieurs problèmes sont apparus. 
RAS
Appeler le endpoint `matomo_dashobard`.
```
http -v POST …
```

fix: filtre les membres actifs dans nbNotbookWith2MembersOrMore

---

app/src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProUpdate.svelte

La checbox RQTH se retrouve collée au champ du dessus.
On ajoute un padding top.
On s'assure que la checkbox RQTH est bien espacée comme il faut.
fix #1745

fix: problèmes d'affichage de la donnée RQTH dans le formulaire du diagnostic sociopro

---

app/elm/DiagnosticEdit/RomeSelect.elm
app/elm/Pages/Pro/Carnet/Action/List/ActionSelect.elm
app/elm/Pages/Pro/Carnet/Action/List/Page.elm
app/elm/UI/SearchSelect/Component.elm
app/tests/Pages/Pro/Carnet/Action/List/Tests.elm

Auparavant, les actions de thème courant étaient affichées en premier, ce n'est plus le cas suite à une régression introduite par le refactoring des actions.
On ajoute une fonction de post processing générique au composant Select, fonction appliquée après la réception du référentiel des actions du serveur. Dans notre cas, nous utilisons une fonction qui fait la concaténation de deux listes : la première étant celle des actions ayant un thème identique au thème courant, la deuxième étant le reste des actions. On trie chaque groupe par ordre alphabétique.
Se rendre sur la review app https://cdb-app-review-pr1743.osc-fr1.scalingo.io/
Charger la liste des actions et s'assurer que les actions du thème courant sont bien en haut et que les autres arrivent après, cf vidéo ci-dessous.
Fix #1736

fix: affichage des actions du thème courant en premier

---

app/elm/Diagnostic/Main.elm

Fix #1757 
Autoriser l'overflow sur le container dsfr. 
RAS
Afficher un carnet. L'ombre des boites de diagnostic n'est pas coupée.

fix(diagnostic): afficher l'ombre portée par les diagnostics professionnels

---

hasura/migrations/carnet_de_bord/1684934249002_actions_events_are_listed_at_the_starting_at_date/down.sql
hasura/migrations/carnet_de_bord/1684934249002_actions_events_are_listed_at_the_starting_at_date/up.sql

L'historique du carnet affiche les actions à leur date de création. On s'attend à ce que ce soit la date de début.
Fix #1767 
Modifier le trigger record_notebook_action_event_init_trigger.
Je n'ai pas fait de migration de données. Je ne voyais pas comment relier les événements aux actions de manière fiable. Est-ce acceptable ?
Ajouter une action avec une date de début différente de la date du jour. Elle apparait dans l'historique à la date de début sélectionnée.

fix(actions): utiliser la date de début dans l'historique de carnet

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/ui/NotebookEvent/NotebookEventList.svelte
app/src/routes/(auth)/orientation/carnets/edition/[notebook_id]/+page.svelte
app/src/routes/(auth)/pro/carnet/[uuid]/+page.svelte
app/src/routes/(auth)/pro/carnet/_getNotebook.gql
hasura/seeds/carnet_de_bord/seed-data.sql

ETQ CO, je veux pouvoir consulter l'historique de parcours
On extraie l'affichage des évènements dans un composant Svelte pour pouvoir le réutiliser côté CO.
J'ai enlevé du code qui me semblait obsolète de rafraîchissement des events en même temps que le Notebook. A vérifier que le rafraîchissement des events lors du rechargement du Notebook se passe bien.
Se connecter avec un CO (`giulia.diaby` par exemple) et s'assurer que l'on peut voir la liste des actions lorsque l'on est sur un carnet.
fix #1678

feat: ajout de l'historique de parcours pour les Chargés d'Orientation

---

app/src/lib/ui/ProBeneficiaryUpdate/ProBeneficiaryUpdateFields.svelte
app/src/lib/ui/ProNotebookPersonalInfo/ProNotebookPersonalInfoUpdate.svelte
app/src/lib/ui/ProNotebookPersonalInfo/ProNotebookPersonalInfoView.svelte
app/src/lib/ui/forms/Radio.svelte
app/src/lib/ui/views/NotebookView.svelte
app/src/routes/(auth)/structures/[uuid]/carnets/[notebook_id]/+page.svelte
e2e/features/structureAdmin/carnet/edit.feature
e2e/step_definitions/steps.js
hasura/metadata/databases/carnet_de_bord/tables/public_beneficiary.yaml
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_member.yaml

ETQ gestionnaire de structure, je veux pouvoir mettre à jour les informations personnelles des bénéficiaires orientés vers ma structure pour ne pas devoir demander à un des pros de le faire alors que je suis sur le dossier
Fix #1679 
On rend le volet de modification des informations personnelles configurable pour ne pouvoir modifier que les données de contact (email / téléphone) et l'adresse pour les admin de structure.
Se connecter avec un admin de structure comme `jacques.celaire` par exemple. Cliquer sur `Centre Communal d'action social Livry-Gargan` puis sur `28 bénéficiaires non accompagnés` et se rendre sur le carnet de de Lindsay Aguilar. Cliquer sur `Mettre à jour` dans la rubrique des informations personnelles. S'assurer qu'on peut mettre à jour les informations de contact …

feat: permettre aux admin de structures de modifier les informations personnelles

---

app/src/lib/ui/OrientationHeader/OrientationHeader.test.ts
app/src/lib/ui/views/NotebookView.svelte
app/src/routes/(auth)/beneficiaire/+page.svelte
app/src/routes/(auth)/beneficiaire/_getNotebookByBeneficiaryId.gql
app/src/routes/(auth)/structures/[uuid]/carnets/[notebook_id]/+page.svelte
e2e/features/structureAdmin/carnet/appointments.feature
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_appointment.yaml

En tant que gestionnaire de structure, en particulier lorsque j'ai un profil de secrétariat, j'ai besoin de pouvoir modifier certaines informations suite à une action de ma part (vérification manuelle, convocation, ....) ou un contact avec l'usager et je dois notamment pourvoir saisir un rendez-vous et actualiser l'état de présence pour un professionnel de ma structure.
Fixes #1766 
On réutilise le composant d'édition des RDV des professionnels pour les admins de structure.
Se connecter avec un compte « Admin de structure », `jacques.celaire` par exemple. Cliquer sur « Centre Communal d'action social Livry-Gargan », puis sur « 1 Bénéficiaire accompagné », puis sur « Voir le carnet » de Sophie Tifour. S'assurer que la gestion des RDV est bien ce qui est attendu.

feat: Gestion des RDV des bénéficiaires par l'administrateur de structure

---

app/src/app.css
app/src/lib/ui/base/SearchBar.svelte

fix: #1765
Lorsqu'on saisie du texte dans une barre de recherche, alors une icône "supprimer" (croix) de couleur bleu est affichée dans les navigateur basé sur chromium pour effacer la saisie de texte.
On surcharge la classe spécifique au navigateur chromium pour supprimer le style du navigateur
Ce comportement n'est pas présent dans Firefox
Se connecter en tant que `pierre.chevalier`
se rendre du le carnet de sophi tifour
Saisir du texte dans le filtre des évenements dans l'historique de parcours

fix: suppression de l'icone pour vider le champ dans chrome

---

app/elm/DiagnosticEdit/Main.elm
hasura/migrations/carnet_de_bord/1685994546326_smic-hourly-rate-raise/down.sql
hasura/migrations/carnet_de_bord/1685994546326_smic-hourly-rate-raise/up.sql

Le SMIC a été revalorisé au 1er mai 2023, passant de 11,27 € à 11,52 €.
Il faut donc prendre en compte cette valeur lors de l'affichage de l'avertissement en cas de saisie d'un salaire horaire inférieur au SMIC horaire dans la création / modification d'un projet progessionel.
On modifie la seule occurence de la valeur 1127 en 1152 dans la partie front (ELM) qui conditionne l'affichage de l'avertissement.
On migre les données pour modifier toutes les valeurs inférieures à la nouvelle valeur du SMIC horaire (11,52 €) pour correspondre à cette nouvelle valeur.
Attention, aujourd'hui on n'empêche pas d'enregistrer une valeur inférieure au SMIC horaire.
On ne fait qu'afficher un avertissement si la valeur est inférieure au SMIC horaire.
Par chance, nous n'avons aucun projet professionnels dont …

feat: Prise en compte de l'augmentation du montant du SMIC horaire.

---

.github/workflows/test.yml
.pre-commit-config.yaml
scripts/no-commit-on-main-branch.sh

Malgré le réglage de protection de la branche `main` il est possible de commiter sur celle-ci car tous les dev ont un rôle offrant suffisamment de privilèges pour le faire.
On active le hook de `pre-commit` nommé `no-commit-to-branch` qui contrôle qu'aucun commit n'est fait sur une branche nommée `main`.
On désactive explicitement ce hook avec la variable d'environnement `SKIP=no-commit-to-branch` lors de l'exécution de `pre-commit` dans le workflow `test.yml`, qui peut s'exécuter sur `main` mais ne fait pas de commit.
Noter que le worfklow `release.yml` effectue un commit de release sur `main` mais `pre-commit` ne s'exécute pas dans ce contexte.
RAS
Essayer de commiter sur `main`: pour tester la configuration de cette PR avant qu'elle soit présente sur `main`, on peut temporairement …

chore: Ajout d'un precommit hook pour éviter de commiter sur la branche principale.

---

app/src/dsfr-theme-tac.css
app/static/tarteaucitron.init.js
app/static/tarteaucitron.js-1.11.0/lang/tarteaucitron.fr.js
e2e/features/home.feature
e2e/integration/manager/orientationImport.js
e2e/step_definitions/fixtures.js
e2e/step_definitions/steps.js

La popup de consentement est positionnée sur la popup du nps
on déplace la popup de consentement à droite
ras
se connecter en tant que laure.loge

fix: déplacer la popup de consentement aux cookies vers la droite

---

Makefile

La target `make start` ne démarre pas la console comme elle est censée le faire
Ajouter la target hasura-console dont dépend le script start.sh
```bash
make start
```

fix(Makefile): ajout de hasura-console

---

flake.nix

Dans nix la version de node était 16, elle est arrivée en fin de vie.
Mise à jour vers la version 20.
RAS
Dans un shell nix, lancer les tests

chore(nix): passage de node de 16 à 20

---

e2e/features/orientationManager/carnet/focus.feature
e2e/step_definitions/steps.js
hasura/migrations/carnet_de_bord/1687180495589_alter_table_public_notebook_action_drop_constraint_notebook_action_target_id_action_key/down.sql
hasura/migrations/carnet_de_bord/1687180495589_alter_table_public_notebook_action_drop_constraint_notebook_action_target_id_action_key/up.sql

fix #1779 
Le référent a besoin de pouvoir ajouter plusieurs fois une même action comme "Candidater à une offre" car le bénéficiaire peut candidater à plusieurs offres d'emploi et ça permet de tracer le nombre d'offres différentes aux quelles il a répondu. De plus il est déjà arrivé qu'un accompagnateur appel plusieurs fois le 115. Actuellement le système affiche un message d'erreur lorsque l'utilisateur ajoute une action déjà présente dans le tableau des actions.
On enlève la contrainte d'unicité entre le nom de l'action et la target.
Ajouter des actions avec le même nom et s'assurer que cela fonctionne comme prévu.

feat: Permettre l'ajout d'actions en double

---

app/elm/Effect.elm
app/elm/Pages/Pro/Carnet/Action/List/AddForm.elm
app/tests/Pages/Pro/Carnet/Action/List/AddForm_Tests.elm

Les utilisateurs doivent sélectionner une date de début à chaque fois qu'ils souhaitent ajouter une action. Si la date est celle du jour, elle doit être sélectionnée et fait perdre du temps aux utilisateurs.
Présélectionner par défaut la date du jour.
Pas de test elm :(
Ouvrir le carnet de sophie tifour 
Ouvrir l’accordéon d'un objectif 
Valider que la date de l'action est pré-remplie à la date du jour  
fix #1780

feat: initialise la date de début de l'action à la date du jour

---

.github/workflows/deploy_demo.yml
.github/workflows/deploy_production.yml

Une fois qu'un déploiement Scalingo est lancé, il ne peut pas être arrêté. Il ne sert donc à rien d'arrêter les tâches de déploiement en cours si un autre déploiement est demandé — au contraire, il vaut mieux attendre la fin du déploiement Scalingo avant d'en demander un autre.
De même, si le déploiement d'un des services échoue, il n'est pas utile d'abandonner les tâches de déploiement des autres puisque celles-ci sont de toute façon en cours.
On désactive l'annulation d'exécutions en cours (`cancel-in-progress: false`) et l'annulation de jobs parallèles dans la matrice (`fail-fast: false`).

ci: ne pas abandonner un déploiement en cours

---

app/src/routes/(public)/mentions-legales/+page.svelte

La page mentions légales cnotient des erreurs et il manque certaines informations
- Les infos d'hébergemetnt sont fausse, on utilise désormais Scalingo et non plus microsoft.
- L'adresse de contact pour signaler un problème était manquante  
on corrige les infos 
ras
se rendre sur la page `mentions-legales` depuis le bas de page
fix #1822

fix: corrige les mentions légales

---

app/src/routes/auth/login/+layout.svelte

La vidéo de présentation sur la page de connexion n'est plus fonctionnelle. Il semble que le service Nextcloud de la Fabrique Numérique des ministères sociaux ait cessé de l'héberger, ou que le lien soit devenu invalide comma ça avait déjà été le cas par le passé (#1241).
La vidéo est maintenant intégrée dans les assets du projet, évitant la dépendance à un hébergement externe.
Le poids de la vidéo dans le dépôt Git n'est pas négligeable (15-20 Mo) mais cela devrait rester gérable.
Aller sur la _review app_, essayer de lire la vidéo sur la page de connexion.

fix: réparer la vidéo de présentation sur la page de login

---

hasura/schema.graphql

Lors de la pr #1836, la mise à jour du schema graphql n'a pas été mis à jour.
supprimer l'ancienne contrainte sur les actions
qui évitait d'ajouter plusieurs fois la même action
@see #1836
ras
les tests au verts

fix: supprime l'ancienne contrainte d'unicite

---

app/src/routes/api/notebooks/notebook.test.ts
e2e/step_definitions/steps.js
hasura/metadata/actions.graphql
hasura/schema.graphql

amine a remonter un probleme lors de l'envoi de donnée sur l'action `create_notebook`. L'envoi d'un champ postalCode genere un erreur coté hasura. En effet le nom du champ est `postal_code`
On alias  le nom du champ pour qu'il reflete la doc et soit cohérent avec les autres propriétés
les tests au vert !

fix: alias postalCode dans l'action CreateNotebookInput

---

backend/cdb/api/db/crud/beneficiary.py
backend/cdb/api/v1/routers/beneficiary_repository.py
backend/cdb/api/v1/routers/refresh_situations.py
backend/tests/api/test_refresh_situations.py
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/metadata/databases/carnet_de_bord/tables/public_notebook.yaml
hasura/migrations/carnet_de_bord/1688421552435_alter_table_public_notebook_add_column_diagnostic_fetched_date/down.sql
hasura/migrations/carnet_de_bord/1688421552435_alter_table_public_notebook_add_column_diagnostic_fetched_date/up.sql
hasura/schema.graphql

Le rate limit de l'api PE etant assez, il est frequent d'arriver au plafond, ce qui bloque la récupération de diagnostic.
On limite les appels à l'api a 1 par heure pour chaque carnet.
ras
rafrachir plusieur fois la page d'un carnet 
ne pas voir d'alerte sur la page

perf(pe): évite d'appeler l'api PE trop souvent

---

backend/cdb/api/core/init.py
backend/cdb/api/v1/exception_handler.py
backend/cdb/pe/pole_emploi_client.py
backend/tests/pe/test_pole_emploi_client.py
backend/tests/pe/test_pole_emploi_client.test_get_dossier_individu_nominal.approved.json

Actuellement, lorsqu'une erreur 429 remonte, on ne sait pas la détecter facilement
Faire remonter les erreurs http suite au appel PE plus explicitement
ras
fix #1866

fix: affiche les erreurs http de pole emploi

---

backend/cdb/api/v1/routers/refresh_situations.py
backend/cdb/pe/pole_emploi_client.py
backend/tests/pe/test_pole_emploi_client.py

L'authentification à l'API Pôle Emploi de diagnostic échoue en production parce que nous demandons l'accès à des API qui ne nous sont pas ouvertes en production. Or nous n'utilisons pas encore les API en question.
Ne pas demander ces API inutilisées lors de la création du jeton.
Malheureusement c'est uniquement en ciblant la production de pole-emploi.io que l'on peut voir l'effet de ce changement.

fix: ne pas demander les scopes PE inutiles

---

backend/cdb/api/core/logging.py
backend/cdb/api/v1/exception_handler.py
backend/cdb/pe/pole_emploi_client.py
backend/poetry.lock
backend/pyproject.toml
backend/tests/pe/test_pole_emploi_client.py

On ne gere pas les erreurs 429 
On branche un utilitaire pour gérer le réessayer les requetes qui renvoient un code 429
on a brancher le logger de backoff dans l'application pour suivre les rejeux de requetes
```
while true; do curl 'https://cdb-hasura-review-pr1875.osc-fr1.scalingo.io/v1/graphql' -X POST  -H 'content-type: application/json' -H 'x-hasura-admin-secret: admin'   --data-raw '{"query":"mutation MyMutation {   update_notebook(    where: {id: {_eq:\"879a25f0-e10c-4081-bde3-4aef77826d1a\" }}    _set: {diagnosticFetchedAt: null }   ) {     affected_rows   }   refresh_notebook_situations_from_pole_emploi(notebookId: \"879a25f0-e10c-4081-bde3-4aef77826d1a\"){    has_pe_diagnostic }}"}'; done
```

feat: gestion des 429

---

backend/cdb/pe/models/dossier_individu_api.py

L'api dossier individu renvoi un payload avec des champ `dateMiseAJour` et `conseiller` facultatifs or on s'attend la présence du champ comme indiqué dans la documentation (toujours fourni)
On met à jour notre modèle pour accepté des dates facultative
RAS
Pas de procédure actuellement.

fix: passe dateMiseAjour en facultatif

---

backend/cdb/pe/models/dossier_individu_api.py

Le type du payload renvoyé par dossier individu génére une erreur. en effet le champ contrainteIndividuDta.dateDeModification est marqué comme obligatoire or ce dernier est parfois vide.
On indique que le champs est facultatif dans le modele
RAS
Pas de test (à voir si on a des exemple dans les données de recette)

fix: rend le champ dateDeModification facultatif

---

app/elm/Pages/Carnet/Diagnostic/PoleEmploi/Page.elm
app/src/routes/(auth)/carnet/+layout.svelte
app/src/routes/(auth)/carnet/[notebook]/diagnostic-france-travail/+page.svelte
app/src/routes/(auth)/carnet/[notebook]/diagnostic-france-travail/getNotebookBreadCrumb.gql

Actuellement, lorsqu'on affiche le diagnostic Franc Travailn aucun fil d'ariane n'apparait
rajouter un fil d'ariane
ras
se rendre sur le carnet de diane rose avec different profil
voir le fil d'ariane
fix #1881

fix: affiche un fil d'ariane sur la page du diag France travail

---

app/elm/Diagnostic/PersonalSituation.elm

Actuellement, on affiche des erreurs de liés à une tache de fond et qui perturbent l'utilisation
on propose de supprimer ces alertes.
ces alertes n'etant pas testées, aucun tests à été modifiés

fix: remove pe sync alerts

---

app/src/lib/ui/ProNotebookPersonalInfo/ProNotebookPersonalInfoUpdate.svelte
app/src/lib/ui/ProNotebookPersonalInfo/_updateBeneficiaryPersonalInfo.gql
app/src/lib/ui/views/NotebookView.svelte
e2e/features/pro/carnet/sociopro.feature

Actuellement, lorsqu'une personne modifie des infos perso d'un bénéficiaire, on met à jour la date de modification pour tout les membres
On met à jour  la date de modification du carnet seulement pour l'auteur de la modification
on en profite pour fixer un bug d'affichage sur la date de dernière modification (elle prenait la date de modif du premier membre trouvé)
- se connecter en tant que pierre chevalier
- modifier une info perso
- se connecter en tant que sanka
- ne pas voir la sophie tifour en premier dans les carnets modifiés

fix: met à jour seulement le membre concerné par une mise à jour

---

.envrc
flake.nix

Nix ne permet pas de fixer les versions des outils (de manière simple et lisible). Les versions des outils nix sont décidées par la [release Nix en cours](https://search.nixos.org/packages).
Utiliser [ASDF](https://asdf-vm.com/) en complément de nix pour la gestion précise des versions. L'outil a déjà une configuration présente dans le projet. 
Pour lier nix et asdf on passe par le chargement d'un fichier asdf dans le .envrc (en fonction du shell).
```bash
cd carnet-de-bord
which node # $HOME/.asdf/shims/node
which poetry # $HOME/.asdf/shims/poetry
```

chore(nix): 🧑‍💻 gère les versions des outils avec asdf 

---

e2e/features/home.feature

Le test end to end "Demande de consentement" est rouge presque systématiquement sur les PRs. En relançant le job il passe. Les PRs prennent plus de temps à être validées
Ignorer le test. S'il donne trop de faux négatifs, il est néfaste. Je ne comprends pas bien pourquoi ça ne fonctionne pas, mais en attendant de trouver il serait bien d'avoir des résultats plus fiables.
RAS
Les checks doivent passer

chore(e2e): ignore un test e2e non fiable

---

app/__tests__/triggers/lastModifiedAt.test.ts
app/__tests__/triggers/notebookEvent.test.ts
app/src/lib/ui/ProNotebookFocus/ProNotebookFocusCreate.svelte
app/src/lib/ui/ProNotebookFocus/ProNotebookFocusDetails.svelte
app/src/lib/ui/ProNotebookFocus/ProNotebookFocusUpdate.svelte
app/src/lib/ui/ProNotebookFocus/_addNotebookFocus.gql
app/src/lib/ui/ProNotebookFocus/_deleteNotebookFocus.gql
app/src/lib/ui/ProNotebookFocus/_updateNotebookFocus.gql
app/src/lib/ui/ProNotebookFocus/_updateTargetStatus.gql
app/src/lib/ui/ProNotebookTarget/AddNotebookTarget.gql
app/src/lib/ui/ProNotebookTarget/ProNotebookTargetCreate.svelte
app/src/lib/ui/ProNotebookTarget/_mutation.gql
backend/cdb/api/db/crud/notebook_focus.py
backend/cdb/api/db/crud/notebook_target.py
backend/cdb/api/v1/main.py
backend/cdb/api/v1/payloads/notebook_focus.py
backend/cdb/api/v1/payloads/notebook_target.py
backend/cdb/api/v1/routers/notebook_focus.py
backend/cdb/api/v1/routers/notebook_target.py
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_focus.yaml
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_target.yaml
hasura/schema.graphql
scripts/launch_tests.sh

Actuellement les Axes de travail (focus) et les Objectifs (target) sont créés directement par le frontend via une mutation Hasura ce qui rend impossible la synchronisation avec Pôle emploi.
fix #1887 
On utilise une action Hasura et un endpoint Python qui vont nous permettre plus tard de brancher la synchro PE.
Même si la PR est un peu longue, le principe pour chaque `focus`, `target` et chaque `action` Hasura est le même. On rajoute une action Hasura et les types associés. On remplace la requête GraphQL côté client par l'appel à cette action, cette action forward vers un nouveau endpoint python. Dans ce endpoint Python on crée les objets Pydantic nécessaires pour mapper les input, et on fait appel à la requête qui était originalement appelée dans le front.
L'action hasura de `delete` …

refactor: ajout d'une action Hasura pour les notebook_focus et notebook_target

---

backend/cdb/api/core/settings.py
backend/cdb/api/v1/routers/pe_diagnostic/pe_diagnostic.py
backend/cdb/api/v1/routers/pe_diagnostic/pe_diagnostic_io.py
backend/cdb/api/v1/routers/pe_diagnostic/pe_diagnostic_models.py
backend/tests/api/pe_diagnostic/test_pe_diagnostic.py
backend/tests/api/pe_diagnostic/test_pe_diagnostic_api.py
backend/tests/api/pe_diagnostic/test_pe_diagnostic_io.py
hasura/seeds/carnet_de_bord/seed-data.sql

Grâce à l'intégration avec les API Pôle Emploi, le diagnostic France Travail est affiché sur les carnets pour lesquels les API Pôle Emploi fournissent de l'information.
Ces informations ne sont pertinentes que pour les bénéficiaires des départements de l'expérimentation France Travail (ARSA).
Or, actuellement, nous constatons que les API renvoient des informations pour certains bénéficiaires qui ne sont pas dans les territoires concernés. L'impact principal sur Carnet de Bord est que les statistiques de consultation sont faussées.
Fix: #1920 
Dans le champ config du déploiement en base de données, on va chercher un champ "france_travail_pilot", s'il est présent à "true", alors on effectue la synchronisation.
Je n'ai vu nulle part d'endroit pour modifier cette configuration d'un …

feat(pole-emploi): ne pas afficher le diagnostic PE pour les déploiements non pilotes

---

app/src/lib/ui/ProNotebookMember/_addNotebookAppointment.gql
app/src/lib/ui/ProNotebookMember/_updateNotebookAppointment.gql
hasura/migrations/carnet_de_bord/1691064712005_alter_table_public_notebook_appointment_alter_column_date/down.sql
hasura/migrations/carnet_de_bord/1691064712005_alter_table_public_notebook_appointment_alter_column_date/up.sql
hasura/schema.graphql

Une des colonnes de la base utilise un type de données (`timestamp`) qui ignore le fuseau horaire des constantes de date (`2021-01-02T15:30:00+02:00`).
Migrer la colonne pour utiliser le même type que les autres colonnes de date (`timestamptz`), qui interprète un éventuel fuseau horaire dans les constantes.
Aucun impact sur les données stockées, qui continuent d'être considérées comme UTC.
RAS
Fix: #1829

chore(db): utiliser un timestamp avec timezone dans notebook_appointment

---

e2e/integration/manager/orientationImport.js
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_updates_track.yaml
hasura/metadata/databases/carnet_de_bord/tables/tables.yaml
hasura/migrations/carnet_de_bord/1691584295337_track_notebook_updates/down.sql
hasura/migrations/carnet_de_bord/1691584295337_track_notebook_updates/up.sql
hasura/seeds/carnet_de_bord/seed-data.sql

Fix: #1890 
Pour mieux mesure l'impact de carnet de bord on souhaite connaitre la fréquence de modification des carnets par utilisateurice.
Ajouter une table de suivi de ces modifications qui est renseignée lorsqu'une table reliée à un carnet est modifiée.
Les modification suivantes ajoutent une ligne dans la table notebook_updates_track :
- de bénéficiaire
- de rendez-vous
- de situation
- d'action
- de focus
- de target
- le carnet lui-même

feat(KPI): suivre les modification d'un carnet

---

hasura/metadata/databases/carnet_de_bord/tables/public_notebook_update.yaml
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_updates_track.yaml
hasura/metadata/databases/carnet_de_bord/tables/tables.yaml
hasura/migrations/carnet_de_bord/1691584295337_track_notebook_updates/down.sql
hasura/migrations/carnet_de_bord/1691584295337_track_notebook_updates/up.sql
hasura/schema.graphql
hasura/seeds/carnet_de_bord/seed-data.sql

la pr #1951 a été mergée mais la migration contenait une erreur.
```sql
alter table public.notebook_updates_track owner to cdb;
``` 
Le code suivant fonctionne bien en local mais pas sur les environnement scalingo ou l'utilisateur à un nom différent.
On remarque que la migration n'a pas été appliqué sur l'environnement de preprod, ce qui confirme l'erreur. 
En parcourant les log avec `scalingo --region osc-fr1 --app cdb-hasura-preprod logs --lines 100000`
on trouve 
```
"role \"cdb\" does not exist",
```
fixer la migration 
On profite du fait que la migration ne soit pas appliquée pour 
- modifier le nom de la table en notebook_update pour être cohérent avec notebook_visit
- rajouter un trigger sur les projet_pro
On remarque que l'action hasura de mise à jour des info socio / pro / projet …

fix: fix notebook_update migration

---

app/src/lib/ui/OrientationManager/View.svelte

lorsqu'un Chargé d'orientation se connecte et qu'il va sur "mon compte" il est affiché "Gestionnaire de structure" au lien de Chargé d'orientation
changer le wording
ras
- se connecter en tant que `giulia.diaby`
- aller sur mon compte
- voir Chargé d'orientation
fix #1960

fix: affiche le type de compte correct pour les co

---

app/src/routes/(auth)/manager/_getAccountById.gql
app/src/routes/(auth)/manager/professionnels/+page.svelte
app/src/routes/(auth)/manager/sendConnectionEmail/+server.ts
app/src/routes/auth/jwt/_getAccountInfo.gql

ETQ admin, je peux envoyer un lien de connexion a un pro désactivé (CO dans la situation vécue), le lien reçu permet de se connecter, voir qu'il existe des demande de réo, mais ne permet pas d'accéder aux carnets.
désactiver la possibilité d'envoyer un lien pour les compte désactivé (ou même globalement si c'est plus simple).
On en profite pour ne pas remonter les comptes supprimés quand on valide un lien magique
Se connecter en tant que manager.cd93
Afficher les professionnels
Valider l'absence de bouton pour envoyer un courriel de connexion
fix  #1957

fix: bloquer la connection des comptes supprimés

---

app/src/lib/ui/StructureEdit/StructureCreationForm.svelte
app/src/lib/ui/StructureEdit/StructureEditLayer.svelte
app/src/lib/ui/StructureEdit/structure.schema.test.ts
app/src/lib/ui/StructureEdit/structure.schema.ts
app/src/lib/ui/StructureEdit/updateStructure.gql
app/src/lib/ui/StructureList/StructureList.svelte
app/src/routes/(auth)/admin/deployment/_getStructuresForDeployment.gql
app/src/routes/(auth)/manager/structures/[structure_id]/_getStructureById.gql
hasura/metadata/databases/carnet_de_bord/tables/public_structure.yaml
hasura/migrations/carnet_de_bord/1693401046986_alter_table_public_structure_add_column_sensitive/down.sql
hasura/migrations/carnet_de_bord/1693401046986_alter_table_public_structure_add_column_sensitive/up.sql
hasura/schema.graphql

Pour pouvoir obfusquer certains titres de structure, on a besoin de savoir si ce sont des structures considérées comme « sensibles ».
Ajout d'un booléen sur la structure permettant de la marquer comme sensible.
En tant que manager, dans la liste des structures, vérifier que le booléen structure sensible est bien affiché.
Lors de l'édition d'une structure, vérifier que la case à cocher « structure sensible » fonctionne correctement.
fix #1962

feat: possibilité de marquer une structure comme sensible

---

app/src/lib/constants.ts
app/src/lib/ui/NotebookEvent/GetNotebookEvents.gql
app/src/lib/ui/NotebookEvent/NotebookEventList.svelte
app/src/routes/(auth)/pro/carnet/_getNotebook.gql
backend/cdb/api/db/crud/notebook_event.py
backend/cdb/api/db/crud/orientation_info.py
backend/cdb/api/db/models/notebook_event.py
backend/cdb/api/db/models/orientation_info.py
backend/cdb/api/v1/routers/orientations.py
backend/tests/api/test_orientations.py
backend/tests/api/test_orientations.test_change_orientation_with_new_referent.approved.json
backend/tests/utils/approvaltests.py
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_event.yaml
hasura/migrations/carnet_de_bord/1693388929776_add_orientation_event_type/down.sql
hasura/migrations/carnet_de_bord/1693388929776_add_orientation_event_type/up.sql
hasura/schema.graphql

Il est impossible actuellement de pouvoir visualiser l'évolution des types d'accompagnement d'un bénéficiaire. Cela rend compliqué de faire le lien avec le travail d'accompagnement précédemment réalisé et d'éviter de renvoyer les bénéficiaires sur un dispositif déjà mobilisé.
On ajoute dans l'historique une ligne à chaque orientation / réorientation.
En terme de statut, sera en cours jusqu'à une nouvelle (ré)orientation et dans ce cas, le statut doit passer à clos.
On aggrège dans le champs event les infos courantes (dispositif, structure, référent si défini) et leur valeurs précédentes
Se connecter en tant que giulia diaby
aller sur le carnet de sophie tifour
Réorienter dans différent dispositif et voir les évènements correspondant.
fix #1984

feat: historise les changements d'orientation

---

app/src/lib/ui/ProNotebookFocus/ProNotebookFocusDetails.svelte
app/src/lib/ui/ProNotebookTarget/AddNotebookTarget.gql
app/src/lib/ui/ProNotebookTarget/ProNotebookTargetCreate.svelte
app/src/lib/ui/ProNotebookTarget/ProNotebookTargetCreate.test.ts
app/src/lib/ui/ProNotebookTarget/ProNotebookTargetCreateContainter.svelte
app/src/lib/ui/ProNotebookTarget/index.ts
app/src/lib/ui/base/Radio.svelte
app/src/lib/ui/base/Select.svelte
backend/cdb/api/db/crud/notebook_target.py
backend/cdb/api/v1/payloads/notebook_target.py
hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_target.yaml
hasura/migrations/carnet_de_bord/1694023456180_alter_table_public_notebook_target_add_column_user_consent/down.sql
hasura/migrations/carnet_de_bord/1694023456180_alter_table_public_notebook_target_add_column_user_consent/up.sql
hasura/schema.graphql

ETQ pro, j'ai besoin de demander le consentement du bénéficiaire à l'ajout d'un objectif attaché à un contrat
On ajoute une case à cocher pour le consentement du bénéficiaire lorsqu'un contrat est sélectionné.
L'utilisation de yup avec svelte-form-lib pour exprimer le choix (case à cocher obligatoire si un contrat est choisi) s'est révélé compliqué. J'ai décidé de coder la validation coté front de manière indépendante.  
- Se connecter en tant que `pierre.chevalier`
- Aller sur le carnet de `Sophie Tifour`
- Ouvrir l'axe de travail `Logement` 
- Ajouter un objectif.
- Cliquer sur Ajouter 
- Voir les erreurs s'afficher
- Sélectionner un objectif et un contrat
- Voir l'erreur s'afficher
- Cliquer la case 
- Cliquer sur Ajouter 
fix #1985

feat: demande le consentement du bénéficiaire lors de l'ajout d'un objectif à un contrat

---

app/src/lib/ui/base/Footer.svelte
app/src/routes/(public)/declaration-accessibilite/+page.svelte

Obligation légale avant le 31/12 : Ajouter la déclaration d'accessibilité
On ajoute la page avec le texte généré, cf https://github.com/gip-inclusion/carnet-de-bord/issues/2042
Cliquer sur le lien accessibilité dans le Footer et vérifier que tout est ok.
fix #2042

feat: ajout de la déclaration d'accessibilité

---

app/src/routes/(auth)/cguvalidate/+page.svelte
app/src/routes/(public)/cgu/+page.svelte

Le texte des CGU dans le footer n'est pas à jour.
On met à jour le texte avec la bonne version.
Le produit étant en phase de maintenance, j'ai copié/collé le texte dans l'ancien template pour aller au plus vite.
Se rendre sur la recette, cliquer dans le lien CGU du footer et constater que les CGU sont bien à jour.
fix #2057

fix: correction des CGU du footer

---

app/src/lib/ui/ProfessionalList/List.svelte
app/src/lib/ui/ProfessionalList/_deleteAccount.gql
app/src/lib/ui/ProfessionalList/_getProfessionalsForStructure.gql
hasura/metadata/databases/carnet_de_bord/tables/public_account.yaml

Lorsque l'on supprime un professionnel, la valeur de son champ `deletedAt` est mise à la date du jour, mais aucun autre champ n'est modifié : cela rend impossible de recréer un utilisateur avec le même `username` ou le même `email`.
Quand on supprime un professionnel, on ajoute le suffixe `.deleted` + date du jour à son username et son email.
Aucun test n'existant sur cette fonctionnalité et le produit étant en fin de vie, aucun test n'a été ajouté.
Se connecter en tant qu'admin de structure, supprimer un utilisateur et s'assurer dans la base que le `.deleted` a été ajouté au champ `username` de la table `account` et au champ `email` de la table `professional`.
fix #2030

fix: add suffix to deleted accounts

---

app/src/lib/ui/ProNotebookPersonalInfo/ProNotebookPersonalInfoView.svelte
app/src/routes/(auth)/beneficiaire/_getNotebookByBeneficiaryId.gql

L'affichage du NIR dans le carnet de l'usager n'est pas conforme à la loi. En effet, il est visible de certains professionnels qui n'accompagnent pas les personnes (ex : les gestionnaires de structure et les pros qui effectuent une recherche usager de leur territoire).
On supprime le NIR de l'interface et de la requête GQL.
Se rendre sur le carnet de Sophie Tifour et constater que le NIR n'est plus affiché.
fix #2069

fix: remove NIR

---

backend/cdb/api/v1/routers/notebooks_add_members.py
backend/cdb/api/v1/routers/orientations.py
backend/tests/api/test_notebooks_add_member.py
backend/tests/api/test_orientations.py
hasura/metadata/cron_triggers.yaml

cf https://github.com/gip-inclusion/carnet-de-bord/issues/2072
On enlève le cronjob hasura de notification des admins de structure et on enlève le code relatif à l'envoi d'email lors des orientations / réorientations
Se connecter en tant `giulia.diaby` 
1. mail suite à une demande de réorientation
- Aller dans "Autres Bénéficiaire" "orientés"
- chercher jennings
- afficher le carner de Dee Jennings 
- valider la demande d'orientation sur le carnet de Dee Jennings
- Se rendre dans mailtrap et s'assurer qu'aucun nouveau mail n'a été envoyé
3. mails suite à une premier orientation
- Aller dans "Autres Bénéficiaire" "orientés"
- chercher  keller
- afficher le carner de Noel Keller 
- Se rendre dans mailtrap et s'assurer qu'aucun nouveau mail n'a été envoyé
4. mail suite à une réorientation 
- …

fix: suspension de l'envoi des emails d'orientation/réorientation
