.env
.env.sample
.gitignore
migrations/20210715101010_create-account.js
package.json
renovate.json
seeds/04_account.js
src/business/ProfessionalBusiness.ts
src/database/Account.ts
src/database/Professional.ts
src/global.d.ts
src/hooks.ts
src/lib/emails/emailMagicLink.ts
src/lib/guards/index.ts
src/lib/utils.ts
src/lib/variables/index.ts
src/routes/__layout.svelte
src/routes/api/auth/jwt.ts
src/routes/api/auth/login.ts
src/routes/auth/jwt/[uuid].svelte
src/routes/auth/login/index.svelte
src/routes/index.svelte
tailwind.config.cjs
yarn.lock

feat(login): handle magic link

---

.k8s/components/app.ts

Mise a disposition de la variable d'environnement `APP_URL` telle que:
```
root@app-5fb9d4f86-sb94j:/app# env | grep APP_URL
APP_URL=https://carnet-de-bord-app-url.dev.fabrique.social.gouv.fr
```

fix: Add APP_URL.

---

.github/workflows/review.yml
.k8s/components/jobs/restore.ts
CHANGELOG.md
package.json

This one should fix the restore DB problem occurring on `master` branch.

fix: Use k8s-restore-db action.

---

src/lib/ui/HeaderCDB.svelte
src/lib/ui/base/MenuButton.svelte
src/lib/ui/base/MenuListItem.svelte
src/lib/ui/base/menu.ts
src/lib/ui/views/Disconnect.svelte

implemente l'ui de deconnexion ainsi que le bouton en popover
closes #133

feat: add disconnect  ui and dropdown profile icon menu

---

src/routes/auth/jwt/[uuid].svelte
src/routes/auth/jwt/index.ts

feat: handle url target in access link

---

docker-compose.yaml
hasura/seeds/carnet_de_bord/seed-data.sql

mount metadata and migrations folder on docker for local dev so hasura can auto apply migration on startup

fix(hasura): auto handle migration by mounting migration / metadata  

---

src/lib/ui/ProBeneficiaryPersonnalInfos.svelte
src/lib/ui/base/Accordion.svelte
src/lib/ui/base/Accordions.svelte
src/lib/ui/base/MenuButton.svelte
src/lib/ui/base/accordion.ts
src/routes/particulier/index.svelte
src/routes/pro/carnet/[uuid].svelte
tsconfig.json

- Composant accordéon(et intégration dans Pro / Part
- Renommage du BeneficiaryInfo en `ProBeneficiaryPersonnalInfos`
next PR: vue socio pro & historique

feat(ui): add accordeon

---

src/lib/constants/keys.ts
src/lib/graphql/_gen/typed-document-nodes.ts
src/lib/ui/ProBeneficiaryPersonnalInfos.svelte
src/lib/ui/ProBeneficiarySocioProSituation.svelte
src/lib/utils/date.ts
src/routes/particulier/index.svelte
src/routes/pro/carnet/[uuid].svelte
src/routes/pro/carnet/_query.gql

Ajout des infos sociopro d'un bénéficiaire
next pr : Historique des actions

feat(pro): add beneficiary sociopro situation view

---

src/lib/ui/ProNotebookFocus/ProNotebookFocusView.svelte

chore: fix focuses layout

---

.github/workflows/review.yml
.k8s/components/app.ts
.k8s/components/hasura.ts

This reverts commit ee21c6dffcfe6b5c407037170f3eae960a777bac.Reverts SocialGouv/carnet-de-bord#212

fix: Revert registry changes on review branches

---

.github/workflows/production.yml

Reverts SocialGouv/carnet-de-bord#244

fix: Revert registry changes on preprod and prod

---

src/lib/types.ts
src/lib/ui/ProCreationForm/index.svelte
src/lib/ui/ProFormInfo.svelte
src/lib/ui/base/Header.svelte
src/routes/inscription/request.ts

move username field form AccountRequest to Account (thx @Augustin82 )

fix(frontend): remove username from user creation form

---

src/lib/ui/LayerCDB.svelte
src/lib/ui/base/Header.svelte
src/routes/__layout.svelte
src/routes/auth/__layout.svelte

add transition to layer component (and remove a small layout shift due to scroll bar removing)

fix(ui): add transition to layer

---

src/lib/stores.ts
src/lib/ui/base/Header.svelte
src/lib/ui/base/NavBar.svelte
src/lib/ui/base/NavBarItem.svelte

fix(ui): fix menu and mobile

---

src/lib/ui/ProNotebookCreator/ProNotebookCreatorView.svelte
src/lib/ui/ProNotebookMember/ProNotebookMemberView.svelte
src/lib/ui/ProNotebookStructure/ProNotebookStructureList.svelte

fix(ui): update structure display

---

.github/workflows/production.yml

fix: preprod

---

.k8s/yarn.lock

fix: cherry dependabot patch

---

src/lib/ui/utils/LoaderIndicator.svelte
src/routes/admin/__layout.svelte
src/routes/index.svelte
src/routes/manager/__layout.svelte
src/routes/manager/structures/index.svelte
src/routes/manager/utilisateur/[uuid].svelte
src/routes/manager/utilisateurs/index.svelte
src/routes/particulier/__layout.svelte
src/routes/pro/__layout.svelte
src/routes/pro/accueil/index.svelte
src/routes/pro/annuaire/index.svelte
src/routes/pro/carnet/[uuid].svelte
src/routes/pro/moncompte/index.svelte

fix: layer / search

---

hasura/migrations/carnet_de_bord/1637228317847_remove_default_dates_on_add_notebook_member/down.sql
hasura/migrations/carnet_de_bord/1637228317847_remove_default_dates_on_add_notebook_member/up.sql
src/lib/graphql/_gen/typed-document-nodes.ts
src/lib/ui/ProBeneficiaryCreate/ProBeneficiaryCreateForm.svelte
src/lib/ui/ProCreationForm/index.svelte
src/lib/ui/ProFormInfo.svelte
src/lib/ui/ProNotebookMember/ProNotebookMemberForm.svelte
src/lib/ui/ProNotebookMember/ProNotebookMemberInvitation.svelte
src/routes/admin/index.svelte
src/routes/manager/utilisateurs/index.svelte
src/routes/pro/annuaire/_mutation.gql

Fixes pour #381, #385, et #387.

fix: minor fixes for pending issues

---

hasura/metadata/databases/carnet_de_bord/tables/public_structure.yaml

Les droits manquaient pour le role manager.

fix: allow managers to update a structure again

---

hasura/metadata/actions.graphql
hasura/metadata/actions.yaml
src/lib/graphql/_gen/typed-document-nodes.ts
src/lib/ui/AdminDeployment/AdminDeploymentDetail.svelte
src/lib/ui/AdminDeployment/AdminNotebookUpdate.svelte
src/lib/ui/AdminDeployment/_getDeploymentById.gql
src/lib/ui/AdminNotebookUpdate/NotebookListUpdater.svelte
src/lib/ui/AdminNotebookUpdate/_getNotebook.gql
src/lib/ui/AdminNotebookUpdate/_updatenoteBooks.gql
src/routes/actions/_getNotebookInfo.gql
src/routes/actions/update_notebook.ts
src/routes/admin/__layout.svelte
src/routes/admin/deployment/[uuid]/index.svelte
src/routes/admin/index.svelte
src/routes/api/fixtures.json

add a ui to select beneficiary notebook to update

feat: add button to update notebook

---

src/lib/ui/ProNotebookFocus/ProNotebookFocusDetails.svelte

fix: update lint config

---

.eslintignore
.eslintrc.cjs
package.json
src/.eslintrc.cjs

previous PR was misnamed :) this one fix the lint config that should fail whne lint on precommit

chore: update lint config

---

src/lib/ui/base/Footer.svelte
src/lib/utils/redirectUrl.ts
src/routes/mentions-legales/__layout.svelte
src/routes/mentions-legales/index.svelte
src/routes/politique-confidentialite/__layout.svelte
src/routes/politique-confidentialite/index.svelte

feat: add legal notice and privacy policy

---

src/lib/ui/AdminDeployment/AdminDeploymentBeneficiariesImport.svelte
src/lib/ui/PartNotebookPersonalInfo/PartNotebookPersonalInfoView.svelte
src/lib/ui/ProBeneficiaryCreate/index.svelte
src/lib/ui/ProBeneficiarySearchBar.svelte
src/lib/ui/ProFormIdentifiers/ProFormIdentifierCAF.svelte
src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProUpdate.svelte
src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProView.svelte
src/routes/politique-confidentialite/index.svelte

feat: some renaming

---

src/lib/graphql/_gen/typed-document-nodes.ts
src/lib/helpers.ts
src/lib/ui/ProBeneficiaryCreate/beneficiary.schema.ts
src/lib/ui/StructureFormInfo.svelte
src/lib/ui/forms/Form.svelte
src/lib/ui/forms/index.ts
src/lib/ui/structure.schema.ts
src/lib/validation.ts
src/routes/inscription/_getStructures.gql
src/routes/manager/structures/index.svelte

handle structure form errors / validation

fix: handle error in structure form

---

.eslintrc.cjs
src/lib/services/account.ts
src/lib/tracking/matomo.ts
src/lib/ui/AdminDeployment/AdminDeploymentBeneficiariesImport.svelte
src/lib/ui/AdminDeployment/AdminDeploymentList.svelte
src/lib/ui/AdminDeployment/AdminDeploymentProfessionalsImport.svelte
src/lib/ui/AdminDeployment/AdminDeploymentStructuresImport.svelte
src/lib/ui/AdminNotebookUpdate/NotebookListUpdater.svelte
src/lib/ui/PartNotebookPersonalInfo/PartNotebookPersonalInfoView.svelte
src/lib/ui/ProAccount/ProAccountEdit.svelte
src/lib/ui/ProBeneficiaryCreate/index.svelte
src/lib/ui/ProCreationForm/index.svelte
src/lib/ui/ProNotebookCreator/ProNotebookCreatorView.svelte
src/lib/ui/ProNotebookMember/ProWithStructureView.svelte
src/lib/ui/ProNotebookPersonalInfo/ProNotebookPersonalInfoView.svelte
src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProROME.svelte
src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProView.svelte
src/lib/ui/StructureFormInfo.svelte
src/lib/ui/format.ts
src/routes/__layout.svelte
src/routes/actions/update_notebook.ts
src/routes/api/marne.ts
src/routes/auth/jwt/index.ts
src/routes/auth/login/index.ts
src/routes/auth/oubli/index.ts
src/routes/inscription/request.ts
src/routes/manager/confirmPro.ts
src/routes/manager/sendConnectionEmail.ts
src/routes/pro/carnet/invitation.ts
src/routes/pro/queryUser.ts

Use `import type` for types and `import` for values.

fixes: minor fixes + correctly import types

---

src/lib/ui/AdminDeployment/AdminDeploymentCreateLayer.svelte
src/lib/ui/AdminDeployment/adminDeployment.schema.ts

ajout des erreurs dans le formulaire de creation de deploiement

fix: handle error in create deployment form

---

src/lib/ui/AdminDeployment/adminDeployment.schema.ts
src/lib/ui/ProBeneficiaryCreate/beneficiary.schema.ts
src/lib/ui/ProCreationForm/pro.schema.ts
src/lib/ui/structure.schema.ts
src/lib/validation.ts

fix: validation of alphanumerical fields

---

.github/workflows/preproduction.yml
.github/workflows/review.yml
e2e/codecept.conf.js
e2e/features/inscription.feature
e2e/step_definitions/steps.js

j'ai ajouté des mutations en fin de tests pour nettoyer les données créées dans le tests

fix: add cleanup function after e2e tests

---

__tests__/.eslintrc.cjs
__tests__/marne.test.ts
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_action.yaml
hasura/migrations/carnet_de_bord/1641897839853_add_action_target_constraint/down.sql
hasura/migrations/carnet_de_bord/1641897839853_add_action_target_constraint/up.sql
hasura/seeds/carnet_de_bord/seed-data.sql
src/lib/graphql/_gen/typed-document-nodes.ts
src/routes/actions/_getNotebookInfo.gql
src/routes/actions/_updateNotebook.gql
src/routes/actions/update_notebook.ts
src/routes/api/_marne.test.ts
src/routes/api/fixtures.json
src/routes/api/marne.ts
src/routes/api/marne.types.ts
svelte.config.js

handle creation / update of focus
handle creation of new target
handle creation of new action (and avoid recreate already created action)
todo : maybe more comment

feat: update marne parser

---

src/routes/actions/update_notebook.ts
src/routes/api/marne.ts

handle api error (reject on fail)

fix: update parse error handling in api

---

src/lib/graphql/_gen/typed-document-nodes.ts
src/lib/services/account.ts
src/routes/auth/login/_updateAccountAccesskey.gql
src/routes/auth/oubli/index.ts
src/routes/inscription/request.ts
src/routes/manager/_confirmAccountById.gql
src/routes/manager/confirmPro.ts
src/routes/manager/sendConnectionEmail.ts
src/routes/manager/utilisateurs/index.svelte

Nom de branche plus court pour #513

fix: stop confirming account when updating access key

---

src/app.html
src/lib/ui/AdminDeployment/AdminDeploymentProfessionalsImport.svelte

replace phone with mobileNumber

fix: use corect key for phone when import pro

---

hasura/metadata/databases/carnet_de_bord/tables/public_notebook_action.yaml
hasura/migrations/carnet_de_bord/1642686957723_beneficiary_unique/down.sql
hasura/migrations/carnet_de_bord/1642686957723_beneficiary_unique/up.sql

Nom de branche plus court pour #515

fix: replace beneficiary unique constraint

---

src/lib/tracking/matomo.ts
src/lib/ui/ProBeneficiaryCreate/index.svelte
src/lib/ui/ProNotebookAction/ProNotebookActionCreate.svelte
src/lib/ui/ProNotebookContract/ProNotebookContractDetails.svelte
src/lib/ui/ProNotebookFocus/ProNotebookFocusCreate.svelte
src/lib/ui/ProNotebookFocus/ProNotebookFocusDetails.svelte
src/lib/ui/ProNotebookFocus/ProNotebookFocusUpdate.svelte
src/lib/ui/ProNotebookMember/ProNotebookMemberInvitation.svelte
src/lib/ui/ProNotebookMember/ProNotebookMembersView.svelte
src/lib/ui/ProNotebookPersonalInfo/ProNotebookPersonalInfoUpdate.svelte
src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProUpdate.svelte
src/lib/ui/ProNotebookTarget/ProNotebookTargetCreate.svelte
src/lib/ui/base/Video.svelte
src/lib/ui/views/Disconnect.svelte
src/routes/__layout.svelte
src/routes/auth/jwt/[uuid].svelte
src/routes/auth/logout.ts
src/routes/manager/beneficiaires/index.svelte
src/routes/manager/statistiques/index.svelte
src/routes/manager/structures/index.svelte
src/routes/manager/utilisateurs/index.svelte

- fix tracking of page (trackpageView)
- add trackEvent to track activity 
- add custom dimension (role / deployment)

feat: add tracking events

---

.dockerignore
package.json
src/lib/ui/AdminDeployment/AdminDeploymentBeneficiariesImport.svelte
src/lib/ui/AdminDeployment/AdminDeploymentProfessionalsImport.svelte
src/lib/ui/AdminDeployment/AdminDeploymentStructuresImport.svelte
yarn.lock

fix: use a csv parser lib

---

.github/workflows/preproduction.yml
.github/workflows/review.yml
e2e/package.json
e2e/yarn.lock
package.json
yarn.lock

renovate #576, #577, #578, #579

fix: update deps

---

src/lib/tracking/matomo.ts

update dimension id  since I recreated  new action dimensions

fix: update matomo dimension id

---

.github/workflows/deactivate.yml

avec celle-ci la destruction de DB doit fonctionner

chore(ci): fix deactivate action

---

hasura/metadata/databases/carnet_de_bord/tables/public_deployment.yaml
src/global.d.ts
src/lib/chat/Crisp.svelte
src/lib/graphql/_gen/typed-document-nodes.ts
src/lib/stores/crispData.ts
src/lib/stores/index.ts
src/routes/_query.gql
src/routes/pro/__layout.svelte
src/routes/pro/annuaire/index.svelte

Add some extra info to Crisp (some of it does not seem to work).

feat: crisp data store

---

src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProView.svelte

fix: add more context to RSA rights

---

hasura/migrations/carnet_de_bord/1644337776226_education_level/down.sql
hasura/migrations/carnet_de_bord/1644337776226_education_level/up.sql
src/lib/constants/keys.ts

@lionelB le "down" est pas exactement l'inverse du "up" parce qu'on perd la nuance bac+5/bac+8, faut voir si on veut faire quelque chose pour ça ou pas.
fix #603

feat: education level

---

.sonarcloud.properties

chore: exclude generated code from SonarCloud analysis

---

src/lib/constants/keys.ts

fix: add 'Aucune' option for geo mobility

---

src/routes/api/_marne.test.ts
src/routes/api/marne.ts

fix: fix marne api tests

---

hasura/metadata/databases/carnet_de_bord/tables/public_beneficiary_structure.yaml
hasura/metadata/databases/carnet_de_bord/tables/public_notebook.yaml
hasura/metadata/databases/carnet_de_bord/tables/public_notebook_member.yaml
hasura/migrations/carnet_de_bord/1645388112574_benef_struct_uniqueness/down.sql
hasura/migrations/carnet_de_bord/1645388112574_benef_struct_uniqueness/up.sql
hasura/migrations/carnet_de_bord/1645522376586_alter_table_public_notebook_member_add_column_active/down.sql
hasura/migrations/carnet_de_bord/1645522376586_alter_table_public_notebook_member_add_column_active/up.sql
src/lib/graphql/_gen/typed-document-nodes.ts
src/lib/ui/AdminStructure/_addNotebookMembersBatch.gql
src/lib/ui/AdminStructure/_getNotebookForBeneficiary.gql
src/lib/ui/AdminStructure/_removeNotebookMembers.gql
src/lib/ui/Deployment/_DeactivateNotebookMember.gql
src/lib/ui/Deployment/_addNotebookMembersWithBeneficiaryStructureUpdate.gql
src/lib/ui/Dialog.svelte
src/lib/ui/Manager/UpdateNotebookMembers.svelte
src/lib/ui/Manager/_attachBeneficiaryToStructure.gql
src/lib/ui/Tag.svelte
src/lib/ui/base/Alert.svelte
src/lib/ui/base/Button.svelte
src/routes/manager/_getDeploymentInfo.gql
src/routes/manager/index.svelte
src/routes/pro/carnet/[uuid].svelte
src/routes/structures/[uuid]/beneficiaires_en_attente.ts
src/routes/structures/[uuid]/index.svelte
static/fichiers/import_reorientation.csv

mise en place d'un import de fichier avec 4 colonnes
Prénom*|Nom*|Date de naissance*|Accompagnateurs à ajouter|Accompagnateurs à supprimer|Structures à rattacher
--|--|--|--|--|--|
Sophie|Tifour|1982-02-01|jan.ajoute@cd.fr|jean.retire@cd.fr|CD 26
les mails des accompagnateurs doivent etre séparés par des virgules
fix #641

feat: reorientation v0

---

src/routes/auth/jwt/index.ts

add Secure / Cache control and header to setCookie
fix #548

fix: update cookie cache control

---

hasura/metadata/databases/carnet_de_bord/tables/public_admin_structure.yaml
src/lib/ui/AdminStructure/Card.svelte
src/lib/ui/AdminStructure/StructureList.svelte
src/routes/structures/[uuid]/index.svelte
src/routes/structures/index.svelte

fix: admin structure

---

src/routes/actions/create_deployment.ts
src/routes/actions/insert_structure.ts
src/routes/auth/login/index.ts
src/routes/inscription/request.ts
src/routes/manager/confirmPro.ts
src/routes/manager/sendConnectionEmail.ts
src/routes/pro/carnet/invitation.ts

stop waiting until email had been sent

fix: async mail

---

e2e/features/pro/annuaire/recherche.feature
e2e/package.json

test: flakych

---

e2e/features/pro/accueil/recherche.feature
e2e/features/pro/annuaire/recherche.feature

test: try fix flaky test

---

hasura/metadata/databases/carnet_de_bord/tables/public_notebook_target.yaml
hasura/migrations/carnet_de_bord/1646132441749_alter_table_public_notebook_target_add_column_status/down.sql
hasura/migrations/carnet_de_bord/1646132441749_alter_table_public_notebook_target_add_column_status/up.sql
src/lib/graphql/_gen/typed-document-nodes.ts
src/lib/ui/ProNotebookAction/ProNotebookActionList.svelte
src/lib/ui/ProNotebookFocus/ProNotebookFocusDetails.svelte
src/lib/ui/ProNotebookFocus/_getNotebookFocusById.gql
src/lib/ui/ProNotebookFocus/_updateTargetStatus.gql
src/lib/ui/base/Accordion.svelte

Ajout du statut d'un objectif

---

src/routes/actions/matomo_dashboard.ts

fix: matomo endpoitn is a post

---

src/lib/graphql/_gen/typed-document-nodes.ts
src/routes/actions/_getDeploymentStats.gql
src/routes/actions/_matomo_dashboard.test.ts
src/routes/actions/matomo_dashboard.ts

ajout de nouvelles stats pour le dashboard
fix  #685

feat: add stat to matomo_dashboard

---

.env.sample
.env.test.sample
.github/workflows/review.yml
__tests__/annuaire_search.test.ts
__tests__/health.test.ts
docker-compose-test.yaml
package.json
scripts/launch_tests.sh
scripts/shdotenv
src/lib/config/variables/public.ts

./scripts/launch_tests.sh
À faire (plus tard dans une autre PR ?) : 
- Lancer les tests sur la CI
- Avoir des seeds dédiés aux tests
- Tester le code Typescript qui appelle la query

chore: add tests for search

---

e2e/yarn.lock
yarn.lock

chore: update dependencies (dependabot)

---

.github/workflows/lint.yml
.github/workflows/preproduction.yml
.github/workflows/release.yml
.github/workflows/review.yml
package.json
yarn.lock

chore(deps):  tailwing and actions

---

src/lib/ui/views/NotebookView.svelte

fix: remove <br> from  situation display

---

e2e/features/pro/carnet/contract.feature
e2e/step_definitions/fixtures.js
e2e/step_definitions/steps.js
hasura/metadata/databases/carnet_de_bord/tables/public_notebook.yaml
hasura/migrations/carnet_de_bord/1653842432201_add_contract_start_end_dates/down.sql
hasura/migrations/carnet_de_bord/1653842432201_add_contract_start_end_dates/up.sql
src/lib/graphql/_gen/typed-document-nodes.ts
src/lib/ui/ProNotebookContract/ProNotebookContractDetails.svelte
src/lib/ui/ProNotebookContract/_mutation.gql
src/lib/ui/ProNotebookContract/_updateNotebookContract.gql
src/lib/ui/ProNotebookFocus/ProNotebookFocusView.svelte
src/lib/utils/date.ts
src/routes/beneficiaire/_getNotebookByBeneficiaryId.gql
src/routes/pro/carnet/_getNotebook.gql

[#575](https://github.com/SocialGouv/carnet-de-bord/issues/575)

feat: add contract end date in notebook focuses

---

DEPLOY.md

docs: add deploy doc

---

.github/workflows/preproduction.yml
.github/workflows/review.yml
e2e/features/pro/carnet/sociopro.feature
e2e/step_definitions/steps.js
hasura/metadata/databases/carnet_de_bord/tables/public_notebook.yaml
hasura/migrations/carnet_de_bord/1653319594182_alter_table_public_notebook_add_column_work_situation_end_date/up.sql
src/lib/graphql/_gen/typed-document-nodes.ts
src/lib/ui/Beneficiary/SocioProView.svelte
src/lib/ui/ProNotebookMember/_updateNotebookAppointment.gql
src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProUpdate.svelte
src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProView.svelte
src/lib/ui/ProNotebookSocioPro/_UpdateSocioPro.gql
src/lib/ui/base/Input.svelte
src/routes/beneficiaire/_getNotebookByBeneficiaryId.gql
src/routes/pro/carnet/_getNotebook.gql

https://github.com/SocialGouv/carnet-de-bord/issues/816

feat: add work situation end date in notebook

---

.env.sample
.env.test.sample
.github/workflows/review.yml
.kube-workflow/dev/values.yaml
.kube-workflow/preprod/values.yaml
.kube-workflow/values.yaml
__tests__/annuaire_search.test.ts
__tests__/health.test.ts
__tests__/login_as.ts
__tests__/triggers/lastVisited.test.ts
__tests__/triggers/notebookEvent.test.ts
src/global.d.ts
src/hooks.ts
src/lib/config/variables/private.ts
src/lib/config/variables/public.ts
src/lib/graphql/createClient.ts
src/routes/actions/create_deployment.ts
src/routes/actions/insert_structure.ts
src/routes/actions/matomo_dashboard.ts
src/routes/actions/update_notebook.ts
src/routes/auth/jwt/index.ts
src/routes/auth/login/index.ts
src/routes/inscription/request.ts
src/routes/manager/confirmPro.ts
src/routes/manager/sendConnectionEmail.ts
src/routes/pro/carnet/invitation.ts
src/routes/structures/[uuid]/beneficiaires_en_attente.ts

replace VITE_GRAPHQL_API with GRAPHQL_API_URL since it could be only use on serverside

refactor: rename VITE_GRAPHQL_API to GRAPHQL_API_URL

---

backend/scripts/pe-parse.sh

Branchement du script d'import PE

---

DEMO.md
e2e/features/deploiement.feature
e2e/features/manager/importBeneficiaires.feature
e2e/features/manager/importOrientationManager.feature
e2e/features/manager/importStructures.feature
e2e/features/manager/onboardingManager.feature
e2e/features/manager/rattachement.feature
e2e/features/structureAdmin/importProfessionnels.feature
e2e/features/structureAdmin/onboardingAdminStructure.feature
e2e/features/structureAdmin/rattachementBeneficiaires.feature
hasura/seeds/carnet_de_bord/seed-data.sql

docs: add demo account list

---

backend/scripts/pe-parse.sh

poetry n'est disponible dans l'image, il faut appeller directement python

fix: update python cli command

---

src/lib/constants/keys.ts

Ajout du contrat CEJ (contrat d'engagement Jeune) dans la liste des contrats
Fix #770

feat: add cej contract

---

backend/Dockerfile
e2e/step_definitions/fixtures.js

docker images was missing `pe` folder    -__-!

fix: add pe in docker image

---

backend/api/db/crud/external_data.py
backend/cdb_csv/pe.py
backend/tests/test_external_data.py
backend/tests/test_pe_csv_import.py

Garder plusieurs version des historiques des imports

---

README.md

j'ai explicité le process de merge des pr (en gros squash and merge)

docs: add merge strategy

---

e2e/features/admin_cdb/add_manager.feature
e2e/features/admin_cdb/remove_manager.feature
e2e/features/orientationManager/carnet/members.feature
e2e/features/pro/carnet/appointments.feature
e2e/step_definitions/fixtures.js
e2e/step_definitions/steps.js
hasura/metadata/databases/carnet_de_bord/tables/public_account.yaml
hasura/metadata/databases/carnet_de_bord/tables/public_manager.yaml
src/app.html
src/lib/graphql/_gen/typed-document-nodes.ts
src/lib/ui/AdminHome/ConfirmLayer.svelte
src/lib/ui/AdminHome/ManagerTable.svelte
src/lib/ui/AdminHome/deleteManager.gql
src/lib/ui/Deployment/View.svelte
src/lib/ui/Deployment/_getDeploymentById.gql
src/lib/ui/LayerCDB.svelte
src/lib/ui/ProNotebookAction/ProNotebookActionList.svelte
src/lib/ui/ProNotebookMember/ProAppointment.svelte
src/lib/ui/ProNotebookMember/ProNotebookMembersView.svelte
src/lib/ui/ProNotebookPersonalInfo/ProNotebookPersonalInfoView.svelte
src/lib/ui/base/IconButton.svelte
src/routes/admin/deployment/[uuid]/index.svelte
src/routes/pro/carnet/[uuid].svelte

feat: allow admin to remove a  manager

---

backend/api/core/db.py
backend/api/core/settings.py
backend/api/db/crud/beneficiary.py
backend/cdb_csv/models/csv_row.py
backend/cdb_csv/pe.py
e2e/step_definitions/fixtures.js

- update parse value for brsa field
- clean pool connexion to avoid async io error

fix: use OUI as truthy value

---

src/routes/pro/carnet/[uuid].svelte

fix: remove date input in notebook

---

src/lib/ui/ProNotebookAction/ProNotebookActionCreate.svelte
src/lib/ui/base/Accordion.svelte
src/lib/ui/base/Accordions.svelte
src/lib/ui/base/Autocomplete.svelte

fix: reset action field after insert

---

backend/api/db/crud/beneficiary.py
backend/api/db/crud/notebook.py
backend/api/db/crud/out.py
backend/api/db/crud/structure.py
backend/api/db/models/notebook.py
backend/api/db/models/out.py
backend/scripts/export_notebook.py

#931 
Lien de référence Notion : https://www.notion.so/2022-07-18-Sch-ma-de-sortie-VitamimeT-89f97666376541829be8edeaf17f7440

Spécifier le format de sortie de l'API pour VitamimeT

---

src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProUpdate.svelte

Date de situation actuelle socio pro : modification du phrasé

---

e2e/features/pro/carnet/contract.feature
e2e/features/pro/carnet/sociopro.feature
src/lib/ui/ProNotebookContract/ProNotebookContractDetails.svelte
src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProUpdate.svelte

Ajouter un raccourci 24 mois

---

e2e/features/orientationManager/carnet/edit.feature
e2e/features/pro/carnet/contract.feature
e2e/features/pro/carnet/sociopro.feature
src/lib/ui/Beneficiary/SocioProView.svelte
src/lib/ui/ProNotebookFocus/ProNotebookFocusView.svelte
src/lib/ui/ProNotebookSocioPro/ProNotebookSocioProView.svelte

Fix/wording for time durations (#997)

---

.github/workflows/review-scalingo.yml
scripts/link-scalingo-apps.sh

Ajout d'un workflow GitHub actions qui complète la création automatique de review apps par Scalingo, nécessaire parce que les review apps doivent être interconnectées.

ci: add scalingo PR workflow

---

e2e/features/manager/validateAccount.feature
e2e/step_definitions/fixtures.js
e2e/step_definitions/steps.js
hasura/seeds/carnet_de_bord/seed-data.sql
src/routes/manager/confirmPro.ts
src/routes/manager/professionnels/index.svelte
src/routes/manager/sendConnectionEmail.ts

Fix for #1011
On avait oublié d'inverser une négation !
Ajout d'un test e2e pour le parcours de validation.

fix: validate new pro account (#1011)

---

e2e/features/manager/validateAccount.feature
e2e/step_definitions/fixtures.js
src/lib/graphql/_gen/typed-document-nodes.ts
src/routes/manager/professionnels/_query.gql
src/routes/manager/professionnels/index.svelte

Mise à jour de la requête graphql pour récupérer le nombre bénéficiaires par pro / chargé d'orientation
fix #940

feat: add nb beneficiary to pro list

---

src/routes/manager/professionnels/index.svelte

reorder column (and fix wrong column title)

fix: update column

---

src/lib/ui/Manager/ImportBeneficiaries.svelte

fix: improve error message for uniqueness violation

---

backend/api/db/crud/beneficiary.py
backend/api/db/crud/notebook.py
backend/api/db/crud/out.py
backend/api/db/models/action.py
backend/api/db/models/out.py
backend/tests/test_export_notebook.py

VitamineT : ajout du créateur aux actions

---

.github/workflows/preproduction.yml

Se rendre sur la [review app](https://cdb-app-review-pr1108.osc-fr1.scalingo.io).

fix: increase timeout

---

hasura/seeds/carnet_de_bord/seed-data.sql

fix du role de giulia diaby (`referent` » `chargé d'orientation`)  dans les seed
Se rendre sur la [review app](https://cdb-app-review-pr1149.osc-fr1.scalingo.io).

chore: set correct membertype for giulia.diaby

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/ui/ProfessionalList/EditProfessionalAccountLayer.svelte
app/src/lib/ui/ProfessionalList/List.svelte
app/src/lib/ui/ProfessionalList/_getProfessionalsForStructure.gql
app/src/lib/ui/ProfessionalList/_updateProfessionalAccount.gql
app/src/lib/ui/base/Accordion.svelte
e2e/features/admin_cdb/remove_manager.feature
e2e/features/structureAdmin/edit_professional.feature
e2e/step_definitions/steps.js
hasura/metadata/databases/carnet_de_bord/tables/public_professional.yaml

closes #901
Un gestionnaire de structure peut avoir besoin de modifier les infos d'un professionel pour diverses raisons :
- changement de mon courriel ;
- changement de son numéro de téléphone ;
- changement de son nom de famille en cas de mariage ;
- etc...
Actuellement, l’absence de possibilité de changer ces infos entraine de mauvaises informations de contact risquant d’être accessibles dans le groupe de suivi ayant pour conséquence de ne plus réussir à faire correctement les orientations/rattachement et les réorientations (aujourd’hui basées sur l’adresse mail du professionnel).
On ajoute un bouton `Mettre à jour` dans la liste des professionnels d'une structure.
Celui-ci affiche un formulaire permettant l'édition des informations du professionel :
- prénom
- nom
- courriel
- numéro …

feat: Modification d'un professionel par le gestionnaire de structure.

---

DEMO.md

Ajout du compte `samy.rouate` dans le document des comptes de démos
Se rendre sur la [review app](https://cdb-app-review-pr1269.osc-fr1.scalingo.io).

docs: mise à jour comptes de démo

---

scripts/create-review-apps.sh

Lors de la création de _review app_, notre script n'attend pas que l'application soit "complètement" créée avant de lancer le déploiement. Ceci peut créer une _race condition_ parce que le déploiement s'exécute avant qu'une base de données PostgreSQL ne soit disponible.
On ajoute une boucle d'attente de la création de la base de données avant de faire le déploiement.
Constater que la _review app_ Hasura est créé de façon fiable.
Se rendre sur la [review app](https://cdb-app-review-pr1299.osc-fr1.scalingo.io).

ci(review-apps): attendre le déploiement de PG avant de déployer Hasura

---

app/src/routes/(public)/politique-confidentialite/+page.svelte

La politique de confidentialité n'est plus à jour
on met à jour les infos en utilisant [le contenu à jour](https://instinctive-tarragon-76f.notion.site/Politique-de-confidentialit-_V3-50c56a75324d4e54b0f7550b7871b16c) 
Suivre le lien en pas de page 
Se rendre sur la [review app](https://cdb-app-review-pr1308.osc-fr1.scalingo.io).

fix: Mise à jour de la politique de confidentialité

---

docs/adr/20221004.choix-de-elm.md

Nous considérons l'utilisation de Elm pour la réécriture de Front et avons besoin d'en discuter entre développeurs.
Proposer un ADR pour discuter autour de l'utilisation de Elm
Se rendre sur la [review app](https://cdb-app-review-pr1155.osc-fr1.scalingo.io).

docs: add Elm ADR

---

app/static/robots.txt

Il manque un fichier robot.txt qui est démandés par les crawlers et autres robot errants du web
AJouter un fichier robots.txt
On choisi de bloquer le contenu du site aux robots car l'essentiel du site nécessite une compte utilisateur.
nope :robot: 
Se rendre sur la [review app](https://cdb-app-review-pr1342.osc-fr1.scalingo.io).

feat: ajout d'un fichier robots.txt

---

app/src/routes/+page.svelte

Le lien vers le formulaire n'est plus correct.
Changer le lien de l'accueil par le lien vers le formulaire de demande de démo mis à jour.
RAS.
Se rendre sur la [review app](https://cdb-app-review-pr1370.osc-fr1.scalingo.io).
Cliquer sur "Demander une démo".
Vérifier que le formulaire Google est bien affiché.

feat: Mise à jour du lien vers le formulaire de demande de démo.

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
app/src/lib/ui/ProAccount/ProAccountEdit.svelte
app/src/lib/ui/ProCreationForm/index.svelte
app/src/lib/ui/ProCreationForm/pro.schema.ts
app/src/routes/(auth)/manager/bienvenue/+page.svelte
app/src/routes/(auth)/pro/bienvenue/+page.svelte
app/src/routes/(auth)/pro/moncompte/_mutation.gql
backend/cdb/api/_gen/schema_gql.py

Suite à la suppression de l'inscription, la mise à jour des codegen à été omise. Cela a masque un problème de type manquants 
On met à jour les fichiers de codegen graphql et on fixe les erreurs.
pas d'erreur... on est content
Se rendre sur la [review app](https://cdb-app-review-pr1446.osc-fr1.scalingo.io).

fix: mise à jour des codegen gql

---

e2e/features/pro/carnet/focuses.feature
hasura/migrations/carnet_de_bord/1674589230652_update-referentiel-situations/down.sql
hasura/migrations/carnet_de_bord/1674589230652_update-referentiel-situations/up.sql

Dans le cadre de l'amélioration continue, suite au dernier retour d'enquête utilisateur, amélioration du référentiel situation et objectifs.
On utilise l'[outillage](../carnet-de-bord-outils-referentiel) pour mettre générer le fichier de migration permettant de modifier / ajouter / supprimer et fusionner les situations du référentiel.
RAS
Se rendre sur la [review app](https://cdb-app-review-pr1470.osc-fr1.scalingo.io).
Se rendre sur un carnet de bord en écriture. Par exemple, en tant que pierre.chevalier sur le carnet de Sophie Tifour.
Vérifier que la liste des situations proposées reflète les changements désirés (la référence de ces changements est le fichier dans l'issue #1437).
closes #1437

feat: Mise à jour du référentiel de situations, d'objectifs et d'actions.

---

app/src/lib/ui/Beneficiary/NotebookMembers.svelte
app/src/lib/ui/ProNotebookMember/ProNotebookMembersView.svelte

Le code affichant les membres du groupe de suivi est très dupliqué : on fait quasiment deux fois la même chose, une première fois pour les professionnels et une seconde fois pour les chargés d'orientation.
On rationalise le code pour ne faire qu'une seule boucle.
On pourrait refactorer également les deux composants `NotebookMembers` et `ProNotebookMembers` mais ils sont légèrement différents car l'un est utilisé sur les carnets en lecture seule et l'autre sur les carnets en édition.
On préfère ne pas aller plus loin pour le moment.
Se rendre sur la [review app](https://cdb-app-review-pr1481.osc-fr1.scalingo.io).
Si les tests passent alors c'est ok.

refactor: Simplification du code affichant les membres du groupe de suivi.

---

INSTALL.md

Une fote d’aurtograf, et un chemin python incomplet (la commande est lancée depuis le dossier `backend` et non `backend/cdb`).
Ne pas supprimer ce bloc, qui sera mis à jour [automatiquement](.github/workflows/review-scalingo.yml).

chore: typo dans INSTALL

---

backend/cdb/api/core/init.py

chore: retrait de la méthode transaction

---

app/src/lib/graphql/_gen/typed-document-nodes.ts

Plusieurs modifications récentes n’ont pas été reflétée dans le
document.

chore: mise à jour de typed-document-nodes.ts

---

backend/cdb/api/_gen/schema_gql.py

Aurait dû accompagner e43bbf44cd7343f0490e0322d68aacb440c44348.

chore: mise à jour du module généré graphql pour Python

---

app/src/lib/graphql/_gen/typed-document-nodes.ts
backend/cdb/api/_gen/schema_gql.py

chore: mettre à jour les schéma GraphQL

---

.github/ISSUE_TEMPLATE/fonctionnalite.md

Le modèle d'issues n'a pas d'emplacement pour l'impact métier / KPI qui manque parfois pour comprendre l'intéret d'une issues
Ajout d'emplacements Impact métier et KPI au fichier modèle. 

Ajout d'impact métier et KPI au modèle d'issues

---

app/elm/Diagnostic/Main.elm
e2e/features/manager/viewNotebook.feature

Fix #1758 
un -> une
RAS
Regarder le diagnostic d'un carnet.

fix(diagnostic): Correction de la mauvaise conjugaison de RQTH

---

app/elm/Domain/BeneficiaryRights.elm
app/elm/RsaRightNotice/Main.elm

Correction de la typo clot -> clos
fix #1825
Correction de la string et des variables Elm
S'assurer que la faute d'orthographe ci-dessous a bien été corrigée

fix: typo clot -> clos

---

Makefile
app/src/lib/ui/NotebookEvent/NotebookEventList.svelte
app/src/lib/ui/ProNotebookAction/ProNotebookActionList.svelte
app/src/lib/ui/ProNotebookTarget/ProNotebookTargetCreate.svelte
e2e/README.md
e2e/features/pro/carnet/historique.feature
e2e/vocabulaire.feature
scripts/extract-e2e-vocabulary.sh

L'ajout d'une action ne met pas à jour l'historique.
Fix: #1781 
Relier le store en mutation au notebook_events dans urql
J'en ai profité pour ajouter un script qui extrait la liste des éléments de vocabulaire gherkin dans un fichier.
1. Ajouter une action
2. Fermer le volet
3. L'action est affichée automatiquement dans l'historique

feat(historique): mise à jour automatique après ajout d'action

---

app/src/lib/constants/keys.ts

Fixes #1855 
Ajout de constantes ts
Est-ce que c'est bien le seul endroit à modifier ?
- Mettre à jour le diagnostic socio professionnel d'un carnet.
- Dans la liste déroulante des situations actuelles vous trouverez les situations

feat(diagnostic): ajout de deux situations actuelles

---

hasura/migrations/carnet_de_bord/1688627437320_add_new_targets/down.sql
hasura/migrations/carnet_de_bord/1688627437320_add_new_targets/up.sql

Fixes #1854 
Migration Hasura
RAS

feat(objectifs): ajout de deux nouveaux objectifs

---

backend/cdb/api/v1/routers/refresh_situations/refresh_situations_io.py

lors du refactor, on a remis des scopes inutile
on supprime les scopes
ras
plus d'erreurs dans sentry

fix: supprime les scopes inutiles

---

app/elm/Pages/Carnet/Diagnostic/PoleEmploi/Stories.elm

Le deploiement du storybook etait cassé suite à la pr #1879 
On met à jour les données de test du storybook pour qu'elle respecte le modele
ras
merger la PR et valider que le storybook est bien déployé

chore: fix storybook deploy

---

hasura/migrations/carnet_de_bord/1690467448554_add-orientation-type-autre/down.sql
hasura/migrations/carnet_de_bord/1690467448554_add-orientation-type-autre/up.sql

Pour l'issue support #1908 nous avons besoin d'un nouveau type d'orientation nommé `autre`.
On crée une migration permettant d'ajouter le nouveau type d'orientation.
RAS
NA, si l'application fonctionne c'est que la migration a été appliquée.

feat: ajout d'un nouveau type d'orientation

---

.env.sample
.env.test.sample

Un fichier obsolète est présent dans les fichier env.
Supprimer le flag
RAS
RAS

chore(pole-emploi): supprime un flag obsolète des fichiers env

---

app/elm/Diagnostic/PersonalSituation.elm
app/elm/DiagnosticEdit/Main.elm
app/elm/Domain/RefTheme.elm
app/elm/Domain/Situation.elm
app/tests/Diagnostic/MainTests.elm
e2e/integration/manager/orientationImport.js

Fix: #1872 
Tri alphabétique des situations en lecture et en édition
RAS
Afficher le diagnostic en lecture et écriture, les situations sont triées alphabétiquement dans les thèmes.

feat(diagnostic): tri alphabétique des situations

---

.gitignore
app/src/lib/models/Member.ts
app/src/lib/ui/Beneficiary/NotebookMembers.svelte
app/src/lib/ui/BeneficiaryList/List.svelte
app/src/lib/ui/BeneficiaryList/ListWithOrientation.svelte
app/src/lib/ui/BeneficiaryList/ListWithStructure.svelte
app/src/lib/ui/BeneficiaryList/ProSearchResults.svelte
app/src/lib/ui/OrientationManager/NotebookEdit.svelte
app/src/lib/ui/ProNotebookMember/ProNotebookMembersView.svelte
app/src/lib/ui/ProNotebookMember/ProNotebookMembersView.test.ts
app/src/lib/ui/views/NotebookView.svelte
app/src/routes/(auth)/beneficiaire/_getNotebookByBeneficiaryId.gql
app/src/routes/(auth)/orientation/carnets/edition/[notebook_id]/+page.svelte
app/src/routes/(auth)/pro/+page.svelte
app/src/routes/(auth)/pro/_query.gql
app/src/routes/(auth)/pro/annuaire/_searchPublicNotebooks.gql
app/src/routes/(auth)/pro/carnet/[uuid]/+page.svelte
app/src/routes/(auth)/pro/carnet/_getNotebook.gql
app/vite.config.ts.timestamp-1693905049559.mjs
app/vite.config.ts.timestamp-1693905070418.mjs
app/vite.config.ts.timestamp-1693905112545.mjs
app/vite.config.ts.timestamp-1693905133541.mjs
e2e/features/orientationManager/changeBeneficiaryOrientation.feature
e2e/features/pro/carnet/members.feature
e2e/features/pro/carnet/read_only_other_notebook.feature
hasura/metadata/databases/carnet_de_bord/tables/public_orientation_system.yaml

Pour gagner en lisibilité, il nous a été demandé d'afficher le dispositif d'accompagnement du bénéficiaire dans le carnet ainsi que dans les listes pour tous les professionnels (manager, CO, professionnel).
Fix #1983 
Afficher le dispositif dans les listes de bénéficiaires et les différentes vues du carnet.
RAS
Vérifier que le dispositif est affiché dans les listes et les carnets des bénéficiaires qui sont attachés à un dispositif avec un référent. 
Vérifier que le dispositif n'est pas affiché quand le bénéficiaire n'en a pas.

feat(app): afficher les dispositifs des bénéficiaires

---

hasura/metadata/actions.yaml

[La requête graphql de mise à jour des informations pôle emploi plante très fréquemment et pollue le canal de monitoring](https://sentry.gip-inclusion.cloud-ed.fr/organizations/gip-inclusion/issues/1669/?project=3&referrer=webhooks_plugin)
Autoriser tous les profils à demander la synchronisation.
RAS
RAS

fix(app): autorise la syncro pe pour tous les rôles

---

app/src/routes/(public)/politique-confidentialite/+page.svelte

Fix: #2012 
RAS
RAS
Vérifier la correspondance avec le fichier https://mattermost.incubateur.net/betagouv/pl/a3xtn4axjjr6zrs71udbkt1kda

feat: modification de la politique de confidentialité

---

README.md
app/src/lib/ui/base/Header.svelte
app/src/routes/(auth)/cguvalidate/+page.svelte
app/src/routes/(public)/cgu/+page.svelte

fix https://github.com/gip-inclusion/carnet-de-bord/issues/2071

fix: changement de nom du ministère

---

app/src/routes/(public)/mentions-legales/+page.svelte
app/src/routes/(public)/politique-confidentialite/+page.svelte

Mise à jour des mentions légales et politique confidentialité
fix #2066 and fix #2067
Vérifier que tout est ok sur la review app

fix: mise à jour des mentions légales et de la politique confidentialité
